### PR TITLE
add learning fpv skill

### PR DESCRIPTION
**Pull request by davidjpeacock**
Adds skill covering how to learn FPV Drone flying

### CODE REVIEW

**Comment by davidjpeacock** [comment]
Ok so this PR went from no response to goalposts moved to closed in the space of 3 days. If you're looking for the best method to alienate your contributors, this is a fine way to go about it.

Please let me know if I am welcome to amend my PR and re-propose this.  And for future reference, it would be polite to communicate with people in English when they have made the time to contribute.

**Comment by jjasghar** [comment]
this is how to Refork (fix) your PR for taxonomy and resubmit: https://youtu.be/x6NfWvrkjnI it seems we ran into a problem with the private to public conversion.

**Comment by davidjpeacock** [comment]
Thank you. Apologies. ☺️

**Comment by n1hility** [comment]
Thank you for your contribution to InstructLab! Unfortunately, once a Github repo is made public, all open PRs are automatically closed since they link against a private repo. We have detected that your PR might have been one of the ones affected by this change. If you are still interested in contributing your improvement, please fill out the following short form by no later than May 3rd, and we will get back to you with the additional steps necessary once we have had time to assess the PRs of those still interested:

https://forms.gle/V7SrPPMZDo6iGDYu8

**Pull request closed without merging**
