### PR TITLE
Skeleton Knowledge Taxonomy

### PR DESCRIPTION
**Pull request by mingxzhao**
PR to create skeleton knowledge taxonomy loosely based on https://en.wikipedia.org/wiki/Outline_of_academic_disciplines. 
Thanks for the input and suggestion @spacew

### CODE REVIEW

**Comment by kelbrown20** [comment]
Hey Ming! Do you think you could add `_` instead of spaces between the files names?

**Comment by mingxzhao** [comment]
Will do asap, sorry for the delay!

**Comment by mingxzhao** [comment]
Should be fixed @kelbrown20

**Comment by jjasghar** [comment]
I really, really wish we could merge this.

**Review by jjasghar — APPROVED** [review]

**Comment by jjasghar** [comment]
Proposed via https://github.com/instructlab/dev-docs/pull/46

**Review by hickeyma — CHANGES_REQUESTED** [review]
This should not be merged until https://github.com/instructlab/dev-docs/pull/46 is merged and all feedback is taken on board.

**Comment by hickeyma** [comment]
@mingxzhao Should this follow wikipedia as is. Asking because there seems to be no Humanities content (see https://en.wikipedia.org/wiki/Wikipedia:Contents/Humanities).

**Comment by mingxzhao** [comment]
I chose to stray a bit and incorporate some academia discipline divisions, I mainly wanted to get coverage of as many disciplines as possible and built off of Wikipedia info. Wikipedia "taxonomy" is not really an easy tree to follow so I am not sure it necessarily could be an exact copy. Any suggestions or changes are welcome, so far the whole thing is still empty so changes should be made now.

**Pull request merged**
