### PR TITLE
Phoenix Constellations (combined)

### PR DESCRIPTION
**Pull request by jjasghar**
This is the combined Phoenix Constellations PRs from Red Hat Summit 2024.

This superseeds #899 #940 #947 #950 #980 #999 #1009 #1025 #1042 #1056

### CODE REVIEW

**Comment by jjasghar** [comment]
@instructlab-bot precheck

**Comment by jjasghar** [comment]
@instructlab-bot precheck

**Comment by mcorbin-ibm** [comment]
Per the new taxonomy (#1215 ), I recommend that this knowledge go here:

`knowledge/science/astronomy/constellations/phoenix/`

**Comment by jjasghar** [comment]
Hi! 👋
Thank you for submitting this PR. We are ready to do some validation now, and we have a few candidates to see if they improve the model.
We some resources to run these release candidates, but we need _you_ to help us. Can you reach out to me either on Slack (@awesome) or email me at awesomeATinstructlab.ai so I can get you access via `ilab model chat`?
We can only run these models for a "week" or so, so please reach out as soon as possible and tell me which one is best for you on this PR.

**Comment by jjasghar** [comment]
This one did not take very well.

It got " Is the Phoenix Constellation part of the Milky Way?" and "Are WASP-4 and WASP-5 solar-type yellow stars?" completely wrong.

/cc @juliadenham

**Comment by ivanbaldo** [comment]
So this means that these will never be merged then?

**Comment by jjasghar** [comment]
We are going to send this to the upstream engineering team to do some investigation on why it's didn't work. It's not "never," just not for the foreseeable future.

**Pull request closed without merging**
