### PR TITLE
Add Beancount skill

### PR DESCRIPTION
**Pull request by bjhargrave**
**Describe the contribution to the taxonomy**
- Adds a skill to record [Beancount](https://github.com/beancount/beancount) transactions from free-form text.

**Input given at the prompt**
```
Record the following in a Beancount ledger: I spent 80 EUR in cash on groceries.
```

**Response that was received**

```
class Grocery {
    description = "Grocery purchases"
    currency = "EUR"
}

record {
    account: Grocery,
    amount: -80,
    clear: true
}                                                                                                                                                                                          │
```

**Response that is now received instead**

```
TBD
```

**Contribution checklist**

- [x] tested contribution with `lab generate`
- [x] `lab generate` does not produce any warnings or errors
- [X] all [commits are signed off](https://github.com/instruct-lab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [X] the `qna.yaml` file was [linted](https://yamllint.com)

### CODE REVIEW

**Comment by bjhargrave** [comment]
@instructlab-bot generate

**Comment by RobotSail** [comment]
To fix this PR run `git rebase -i upstream/main` and set the operations to:
```
drop 1966cef feat(synthetic data): Add script to generate synthetic data readme (#650)
drop cc381ec Updating org name from instruct-lab to instructlab (#711)
pick a8a92d5 Add Beancount skill
```

**Comment by bjhargrave** [comment]
@andreasgerstmayr,

In reviewing the synthetic data generated from the teacher model, it is ok but not great. I think we need make a number of improvements to the yaml and then try SDG again.

1. All the answers use the exact same date. So this date is fixed and not derived from the question. The SDG all uses this date. So the training could lead the model to assume this is the only date.
2. The questions are all very similar in form. They all start `Record the following in a Beancount ledger:`. A diversity of question forms is needed to generate more diverse synthetic data.
3. The questions do not contain enough information (context) to be able to derive the answer. For example:
```yaml
 - question: "Record the following in a Beancount ledger: I paid 12.15 EUR at the bakery."
  answer: |
    2024-01-01 * "Bakery"
      Expenses:Food:Bakery      12.15 EUR
      Assets:Cash
```
From the question, how could one know the answer must be from cash or on what date the transaction occured? Cash not in the question. Nor is the date. Each question needs to have all the relevant context so that the model _could_ generate the answer. Here a better question might be: `Create a Beancount ledger entry showing I paid 12.15 EUR in cash at a bakery on 2023-06-10`. This question includes the date, the amount, currency type, a both sides of the ledger entry.

The q/a should be very diverse. Don't repeat information such as dates, currency amounts and types too much. Use many different sides of ledger entries. The goal with the diversity is to avoid the model memorizing the answers because they are all so similar in the generated synthetic data.

**Comment by andreasgerstmayr** [comment]
@bjhargrave thanks for keeping the PR up for so long! I'll update it with your recommendations next week.

Regarding the date: It'd be cool if the model inserts the current date, but I guess that's not possible?

Regarding cash or bank: It'd be nice if the model would take an "educated guess": for example I'll never pay my car insurance bill or rent in cash.
OTOH, in some other countries it might be common to pay e.g. rent in cash :|. ... I think I'll just add cash or bank to the input question then, as you suggested.

**Comment by bjhargrave** [comment]
> Regarding the date: It'd be cool if the model inserts the current date, but I guess that's not possible?

I am sure the model does not know the current date 😀 

> Regarding cash or bank: It'd be nice if the model would take an "educated guess": for example I'll never pay my car insurance bill or rent in cash.

Yes, but this is a compositional skill. It is performative enhancement to the model. With enough training, perhaps a model could discern the proper pattern. But it could also be wrong. For the purposes of a skill here, we should be as explicit and helpful as possible in the training inputs.



> I'll update it with your recommendations next week.

👍🏻

**Comment by bjhargrave** [comment]
@instructlab-bot precheck

**Comment by bjhargrave** [comment]
@instructlab-bot generate

**Comment by bjhargrave** [comment]
@andreasgerstmayr The generated synthetic data is much better than before but there are still some troublesome generated training examples. See https://instruct-lab-bot.s3.us-east-2.amazonaws.com/sdg-svc-pr-747-42f746401555210b6a098e5924113816cf43448e/sdg_1715014955_qna.yaml.json.yaml.html and see the "inputs" and "targets" for each entry in the yaml. 

This one is interesting since the inputs question includes math (50 * $75). The answer contains the correct amount but LLMs are not good at math, so training examples like these are not useful (IMO).

```text
    2024-04-25 * "Selling shares of XYZ Corporation"
      Assets:Investments:Stocks:XYZ Corporation 3750.00 USD
      Liabilities:Securities_Account
      Assets:Checking
      Income:Capital_Gains:Stocks:XYZ Corporation 3750.00 USD
      ! Sale of 50 shares of XYZ Corporation for $75.00 each, transferring the proceeds to checking account.
```


Ledger does not sum to zero.

```text
    2023-03-05 * "Refund for returned book"
      Liabilities:Receivables:Cash   -25.50 CAD
      Expenses:Miscellaneous:Returns   -25.50 CAD
      Assets:Cash                   25.50 CAD
```

Hallucinated a $10 trading fee which was not mentioned in the inputs question.

```text
    2024-03-10 * "Purchase of XYZ stock"
      Assets:Investments:Stocks:XYZ 2283.50 USD
      Liabilities:Brokerage
      Expenses:Investments:Trading Fees  10.00 USD
      Assets:Checking

    Explanation:

    * The date of the transaction is 2024-03-10.
    * The transaction is labeled as "Purchase of XYZ stock".
    * 50 shares of XYZ stock were purchased at a price of 45.67 USD per share, for a total cost of 2283.50 USD (50 x 45.67).
    * The shares are added to the "Assets:Investments:Stocks:XYZ" account.
    * A trading fee of 10.00 USD is incurred and added to the "Expenses:Investments:Trading Fees" account.
    * The payment for the stock purchase is made from the "Assets:Checking" account.
    * The brokerage firm that facilitated the purchase is added as a liability, as the shares have not yet been paid for in full.
```

**Comment by bjhargrave** [comment]
Given the nature of this skill needing to produce valid beancount ledger entries and the fact that the synthetic data generate produces obviously bad training examples, we will need to conclude that this skill is not a good fit for the LAB technique of InstructLab. 

So I am going to close this PR for now. We may revisit in the future if the teacher model is replaced by a more capable model.

**Comment by bjhargrave** [comment]
> Just out of curiosity, how would I fix that? Do I need a different model (llama3 or something), or instead of 15 examples create learning data with 100, 1000 or more examples?

I am not sure. At this point the teacher model is not able to generate proper synthetic data for beancount. I suspect the proper solution would be to fine-tune the teacher model on a corpus of valid beancount examples to train the teacher model the proper form for beancount examples. But if you had such a corpus, you could use it directly instead of trying to have a teacher model generate synthetic training data :-)



> Or is this task of generating exact outputs difficult in any case, and current models are more suited for free-flow text, where minor inconsistencies can be tolerated?

Certainly for the beancount case. But models can be code-trained on programming language examples and become proficient at generating correct code. I just think for this case you could consider beancount to be a programming language but no model is trained on enough beancount examples to become good at generating valid examples (as the teacher model shows). I don't thin you could use the lab technique to train a non-code-trained model to program in Python :-)

**Comment by andreasgerstmayr** [comment]
That makes sense, thank you for the explanation!

**Comment by alinaryan** [comment]
Thank you for your submission. Here are your results: 
Your PR improved the model performance by 0.27999999999999936 points. 
The model's new score is: 5.213333333333333 
 The old score was: 4.933333333333334 
|||||||||||||||||||||||||||||||||||||||||||||||||||| 52.13333333333333%

**Comment by alinaryan** [comment]
Thank you for your submission. Here are your results: 
Your PR improved the model performance by 0.9666666666666668 points. 
The model's new score is: 5.746666666666667 
 The old score was: 4.78 
||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 57.46666666666667%

**Pull request closed without merging**
