### PR TITLE
taxonomy mermaid diagram

### PR DESCRIPTION
**Pull request by makelinux**
[Preview](https://github.com/RedHat-Israel/instructlab-taxonomy/blob/taxonomy_diagram/docs/taxonomy_diagram.md)
Preview:
image

### CODE REVIEW

**Comment by makelinux** [comment]
@jjasghar, who can review this, please?

**Comment by jjasghar** [comment]
We've had a few conversations about this in the triage meeting, I don't think we've ever landed on how we want this displayed. @kelbrown20 can you put your vote here please?

**Comment by jjasghar** [comment]
Also we https://github.com/instructlab/taxonomy/pull/1215 which will be reorganizing a fair amount of the tree, so we would need to update it as soon as it is merged.

**Comment by kelbrown20** [comment]
I was kinda confused about this bc we already have a taxonomy diagram here https://github.com/instructlab/taxonomy/blob/main/docs/taxonomy_diagram.png

**Comment by makelinux** [comment]
@kelbrown20, the old diagram is in raster png format and is difficult to maintain (not practical at all). The new diagram is in conceptual meta format **mermaid**, which is rendered automatically.  It is very easy to maintain.

**Comment by makelinux** [comment]
@jjasghar, I would like to join to classification discussion. I like to cassificate.

**Comment by jjasghar** [comment]
@makelinux please take a look at https://github.com/instructlab/taxonomy/pull/1215 and put any comments on there you'd like. @mcorbin-ibm has put a ton of work into it and would love more feedback.

**Comment by mcorbin-ibm** [comment]
> The new diagram is in conceptual meta format mermaid, which is rendered automatically. It is very easy to maintain.

@makelinux This is very cool if it can automatically render a taxonomy diagram based on the folders in the repo?  Can it then be pulled into our docs/readme file for the repo?

**Comment by kelbrown20** [comment]
These updates look good to me, @juliadenham I know you wanted to take a look at this as well

**Comment by jjasghar** [comment]
@mcorbin-ibm this is the mermaid diagram. Can we spend a few mins talking about it and I believe we should update it and merge it in for the changes we have.

**Comment by jjasghar** [comment]
a "full version" is here becaues of #1215 

```mermaid
 flowchart TD;
   na[not accepting contributions\n at this time]:::na
   taxonomy --> foundational_skill & compositional_skills & knowledge
   
   foundational_skill:::na --> reasoning:::na
   reasoning:::na --> common_sense_reasoning:::na
   reasoning:::na --> linguistics_reasoning:::na
   reasoning:::na --> locgical_reasoning:::na
   reasoning:::na --> mathematical_reasoning:::na
   reasoning:::na --> temporal_reasoning:::na
   reasoning:::na --> theory_of_mind:::na
   reasoning:::na --> unconventional_reasoning:::na


   compositional_skills --> arts
   compositional_skills --> engineering
   compositional_skills --> geography
   compositional_skills --> grounded
   compositional_skills --> history
   compositional_skills --> lingustics
   compositional_skills --> miscellaneous_unknown
   compositional_skills --> philosophy
   compositional_skills --> religion
   compositional_skills --> science
   compositional_skills --> technology
   
   grounded --> grounded/arts
   grounded --> grounded/engineering
   grounded --> grounded/geography
   grounded --> grounded/history
   grounded --> grounded/lingustics
   grounded --> grounded/miscellaneous_unknown
   grounded --> grounded/philosophy
   grounded --> grounded/religion
   grounded --> grounded/science
   grounded --> grounded/technology

   knowledge --> knowledge/arts
   knowledge --> knowledge/engineering
   knowledge --> knowledge/geography
   knowledge --> knowledge/history
   knowledge --> knowledge/lingustics
   knowledge --> knowledge/miscellaneous_unknown
   knowledge --> knowledge/philosophy
   knowledge --> knowledge/religion
   knowledge --> knowledge/science
   knowledge --> knowledge/technology
   knowledge/science --> animals --> birds --> black_capped_chickadee --> black_capped_chikadee-a & black_capped_chikadee-q
   knowledge/science --> astronomy --> constellations --> phoenix --> phoenix-a & phoenix-q

   black_capped_chikadee-a{attribution.txt}
   black_capped_chikadee-q{qna.yaml}
   phoenix-a{attribution.txt}
   phoenix-q{qna.yaml}
   classDef na fill:#EEE
```

I'll update the PR with something cut down.

**Comment by jjasghar** [comment]
Closing per: https://github.com/instructlab/taxonomy/pull/1279, thank you @makelinux i have updated this PR :)

**Pull request closed without merging**
