### PR TITLE
Tonsil Knowledge

### PR DESCRIPTION
**Pull request by luke-inglis**
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

Knowledge of tonsils

**Input given at the prompt**

What is the location of the Tubal tonsils

**Response from the original model**

Tubal tonsils, also known as ampullary tonsils or infundibulopelvic tonsils, are small clusters of lymphoid tissue found at the junction between the uterine tube (also called the fallopian tube) and the ovary. They play a role in the immune system's defense against potential pathogens that may enter the reproductive tract through the vagina. The exact positioning of tubal tonsils can vary slightly among individuals, but they are generally located near the fimbriated ends of the uterine tubes, which are responsible for capturing and transporting ova to the uterus during each menstrual cycle.

**Response from the fine-tuned model**

I did not try the CLI

**Contribution checklist**

- [ ] The contribution was tested with `lab generate`
- [ ] No errors or warnings were produced by `lab generate`
- [x] All [commits are signed off](https://github.com/instruct-lab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x] The `qna.yaml` file contains at least 5 `seed_examples`
- [x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)

### CODE REVIEW

**Review by juliadenham — APPROVED** [review]
Fix signoff and whitespace errors, otherwise it looks good to me!

**Review by juliadenham — APPROVED** [review]
LGTM

**Review by aakankshaduggal — COMMENTED** [review]
@luke-inglis - These two changes are required for the backend.

**Comment by n1hility** [comment]
Thank you for your contribution to InstructLab! Unfortunately, once a Github repo is made public, all open PRs are automatically closed since they link against a private repo. We have detected that your PR might have been one of the ones affected by this change. If you are still interested in contributing your improvement, please fill out the following short form by no later than May 3rd, and we will get back to you with the additional steps necessary once we have had time to assess the PRs of those still interested:

https://forms.gle/V7SrPPMZDo6iGDYu8

**Comment by alinaryan** [comment]
Thank you for your submission. Here are your results: 
Your PR improved the model performance by 0.03703703703703698 points. 
The model's new score is: 0.7407407407407407 
 The old score was: 0.7037037037037037 
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 74.07407407407408%

**Comment by alinaryan** [comment]
Thank you for your submission. Here are your results: 
Your PR decreased the model performance by 0.03703703703703709 points. 
The model's new score is: 0.8148148148148148 
 The old score was: 0.8518518518518519 
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 81.48148148148148%

**Pull request closed without merging**
