### PR TITLE
docs: examples in README intentionally lack 5 q/a pairs

### PR DESCRIPTION
**Pull request by ebblake**
Commit 81700788e (merge #434) and others have modified lines in README.md to mention requiring 5 examples, but then go on with only 3 or 4.  Add some text to make it obvious that, for the sake of brevity, the README file is only listing a snippet of the actual file that may be longer.

Fixes: #434

**Contribution checklist**

- [ ] The contribution was tested with `lab generate`
- [ ] No errors or warnings were produced by `lab generate`
- [X] All [commits are signed off](https://github.com/instruct-lab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [ ] The `qna.yaml` file contains at least 5 `seed_examples`
- [ ] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)

### CODE REVIEW

**Review by lehors — APPROVED** [review]
Good point! Thanks.

**Review by juliadenham — APPROVED** [review]
I agree this change will help clarify some of the confusion!

**Review by kelbrown20 — APPROVED** [review]
These changes also lgtm

**Review by mairin — APPROVED** [review]
LGTM although it might be better to have 5 actual examples :-) for another time!

**Pull request merged**
