### PR TITLE
adding skill for removing any table column

### PR DESCRIPTION
**Pull request by spacew**
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

- This skill adds further capability for markdown table editing, specifically on deleting any columns. 

**Input given at the prompt**

```
  Remove the second column from the following table 
    | First Initial | Last Name  | Company |
    | ------------- | ---------- | ------- |
    | a             | smith      | xyz     |
    | b             | jones      | xyz     |
    | c             | george     | abc     |
    | d             | hicks      | xyz     |
    | e             | long       | abc     |
    | f             | parker     | abc     |
    | g             | burn       | xyz     |
    | h             | talbot     | abc     |
    | i             | washington | abc     |

```

**Response from the original model**

```
╭─────────────────────────────────────────────────────────────── models/granite-7b-lab-Q4_K_M.gguf ───────────────────────────────────────────────────────────────╮
│                                                                                                                                                                 │
│ We can remove the second column using the Pandas `drop()` function with the parameter `columns=[1]`. This will remove the column at index 1, which is the       │
│ second column in our table.                                                                                                                                     │
│                                                                                                                                                                 │
│ ```python                                                                                                                                                       │
│ import pandas as pd                                                                                                                                             │
│                                                                                                                                                                 │
│ df = pd.DataFrame({'First Initial': ['a', 'b', 'c', 'd', 'e', 'f'],                                                                                             │
│                    'Last Name': ['smith', 'jones', 'george', 'hicks', 'long', 'parker'],                                                                        │
│                    'Company': ['xyz', 'xyz', 'abc', 'xyz', 'abc', 'xyz']})                                                                                      │
│                                                                                                                                                                 │
│ df_new = df.drop(['Second Column'], axis=1)                                                                                                                     │
│ print(df_new)                                                                                                                                                   │
│ ```                                                                                                                                                             │
│                                                                                                                                                                 │
│ The output will be:                                                                                                                                             │
│                                                                                                                                                                 │
│ ```                                                                                                                                                             │
│    First Initial Last Name Company                                                                                                                              │
│ 0   a          smith      xyz                                                                                                                                   │
│ 1   b          jones      xyz                                                                                                                                   │
│ 2   c          george     abc                                                                                                                                   │
│ 3   d          hicks      xyz                                                                                                                                   │
│ 4   e          long       abc                                                                                                                                   │
│ 5   f          parker     abc                                                                                                                                   │
│ ```                                                                                                                                                             │
│                                                                                                                                                                 │
│ This means that the `drop()` function has successfully removed the second column from the original DataFrame.                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── elapsed 42.493 seconds ─╯
>>>  
```

**Response from the fine-tuned model**

```
  I don't have the hardware to finetune the model. 
```

**Contribution checklist**

- [x] The contribution was tested with `ilab generate`
- [x] No errors or warnings were produced by `ilab generate`
- [x] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x] The `qna.yaml` file contains at least 5 `seed_examples`
- [x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [x] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [x] Content does not include PII or otherwise sensitive or confidential information
- [x] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

### CODE REVIEW

**Review by jjasghar — CHANGES_REQUESTED** [review]
Please fix the listing issues mentioned here: https://github.com/instructlab/taxonomy/pull/1141/files.

**Comment by jjasghar** [comment]
Please fix the DCO :)

**Comment by spacew** [comment]
I tried so many times fixing it with different combinations of possiblities 😅 Now I am pulling my hair .... Can you please take a look and see what went wrong? @jjasghar 

> Commit sha: [0bed9ad](https://github.com/instructlab/taxonomy/pull/1141/commits/0bed9addb2455fdc4e2d862e945d459bc51a565b), Author: HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com), Committer: HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com); Expected "HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com) [huiwugsa@cccxl010.pok.ibm.com](mailto:huiwugsa@cccxl010.pok.ibm.com)", but got "spacew [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com)".
> Commit sha: [4089483](https://github.com/instructlab/taxonomy/pull/1141/commits/4089483dca71c8107c906135b721fbbe8153d453), Author: HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com), Committer: HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com); The sign-off is missing.
> Commit sha: [6b144dd](https://github.com/instructlab/taxonomy/pull/1141/commits/6b144dd85d259a9f4393a29b7834516e4563d080), Author: HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com), Committer: HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com); The sign-off is missing.
> Commit sha: [dad23f8](https://github.com/instructlab/taxonomy/pull/1141/commits/dad23f8248442f082c4c05bbdbb32488415bacb0), Author: HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com), Committer: HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com); The sign-off is missing.
> Commit sha: [0e3e27f](https://github.com/instructlab/taxonomy/pull/1141/commits/0e3e27fe14849573a36df2a63c0db69f2224c7e3), Author: HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com), Committer: HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com); Expected "HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com) [huiwugsa@cccxl010.pok.ibm.com](mailto:huiwugsa@cccxl010.pok.ibm.com)", but got "spacew [hwulife@gmail.com](mailto:hwulife@gmail.com)".
> Commit sha: [1e9da5f](https://github.com/instructlab/taxonomy/pull/1141/commits/1e9da5f1f0dd59a755e4f6427274b0d606f7a81c), Author: HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com), Committer: HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com); The sign-off is missing.
> Commit sha: [bc2f1bd](https://github.com/instructlab/taxonomy/pull/1141/commits/bc2f1bd8c3f8a62b642918977f5c10b5249cb75e), Author: HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com), Committer: HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com); The sign-off is missing.
> Commit sha: [6b4288b](https://github.com/instructlab/taxonomy/pull/1141/commits/6b4288b529b9ea251c058113178630c0f685c582), Author: HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com), Committer: HUI WU [wuhu@us.ibm.com](mailto:wuhu@us.ibm.com); The sign-off is missing.

**Comment by spacew** [comment]
Hi, @mingxzhao , do you have any idea on what is there to fix for DCO in this latest commit https://github.com/instructlab/taxonomy/pull/1141/commits/7e51c859cd013761dd760e93abe7788d8fab0b0b ?

It looks correct to me.

**Comment by mingxzhao** [comment]
Sorry for the late reply, what ended up fixing this for you?

**Comment by mingxzhao** [comment]
@instructlab-bot precheck

**Comment by spacew** [comment]
@jjasghar had a call with me and did his Git magic 🪄on this and helped me resolved the DCO issue! 

The lesson is -- always working on branches not on main.

**Comment by spacew** [comment]
@mingxzhao I should have worked on a branch on my repo rather than using main. 

What is the next step for this -- should this now to go through triaging?

**Comment by mingxzhao** [comment]
Yes I can go ahead and triage, however, you will have trouble making future contributions until this is merged because of the issue of working from main. If you would like you can close this then resubmit from a branch if you'd like to be able to make other contributions.

**Comment by nerdalert** [comment]
@instructlab-bot precheck

**Comment by spacew** [comment]
Hi, @mingxzhao, for future PRs on other skills/knowledge, I will make sure to work on branches. 

But are you saying that this PR will have trouble getting merged even if it is triage-approved? If that is the case, I can re-submit this one.

**Comment by mingxzhao** [comment]
Sorry for the late reply, I just meant that it is a bit difficult to make further contributions from the fork before your PR is merged or closed, but it would not affect it's ability to be merged. That said it seems this one can be rejected as the model performs this skill very well.

**Comment by spacew** [comment]
Hi, @mingxzhao , I don't think the decision is right on this though ... Looking into the log, the model is not doing a good job removing columns at all: 

https://instruct-lab-bot.s3.us-east-2.amazonaws.com/precheck-pr-1141-83540c9e1be40d9ecd8c2feca2b1b5aa010bbca2-job-368/chat_2024-06-04T18_24_17.log
https://instruct-lab-bot.s3.us-east-2.amazonaws.com/precheck-pr-1141-83540c9e1be40d9ecd8c2feca2b1b5aa010bbca2-job-368/chat_2024-06-04T18_24_15.log

**Pull request closed without merging**
