### PR TITLE
Skill: Teaching Basic Linear Equations (offshoot of #1077)

### PR DESCRIPTION
**Pull request by matteopulcini6**
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

- To teach a language model how to solve simple two-variable linear equations
  using substitution and elimination.
- Teaches tricks like substitution and elimination instead of core math skills 

**Input given at the prompt**

```
   Solve the system of equations: 5x + 2y = 20 and x - 3y = -6  
```

**Response from the original model**

```
    So, the solution to the system of linear equations is x = 14/5 and y = 3
```

Screenshot 2024-05-17 at 11 11 06 AM

**Response from the fine-tuned model**

```
│ So, the solution is (x, y) = (13 / 3, 17 / 3).                                                                                                                           
```

Screenshot 2024-05-17 at 1 40 33 PM

Logic breakdown

**Contribution checklist**

- [ x] The contribution was tested with `ilab generate`
- [ x] No errors or warnings were produced by `ilab generate`
- [ x] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [ x] The `qna.yaml` file contains at least 5 `seed_examples`
- [ x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [ x] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [ x] Content does not include PII or otherwise sensitive or confidential information
- [ x] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

### CODE REVIEW

**Comment by matteopulcini6** [comment]
@jjasghar I created an offshoot for https://github.com/instructlab/taxonomy/pull/1077

**Comment by jjasghar** [comment]
I still really think this is Math. I'll bring it up in our triage meeting on Monday to discuss this with the team.

**Comment by matteopulcini6** [comment]
@jjasghar Sure, during the triage meeting, if there are any suggestions to adjust the PR please let me know and I can apply them.

**Comment by jjasghar** [comment]
This is math again, and we can't accept math.

LLMs aren't great at counting, math, or computation. Right now we're not seeking to improve the model's math and computation ability, as they're example of a different foundational skill than Writing.

Rejecting for now and we can reconsider if we open a math / computation taxonomy.

**Pull request closed without merging**
