### PR TITLE
Add information about running the linter.

### PR DESCRIPTION
**Pull request by laurachiticariu**
Update readme.md to specify one can run a script to check the yaml linter will pass on the PR.
@bjhargrave

### CODE REVIEW

**Comment by jjasghar** [comment]
I like this idea, but my nerd brain is telling me that we should chew on this before approving it. We need to make sure we aren't "bloating" the read me especially if we are starting the docs site soon.

/cc @kelbrown20 @juliadenham

**Comment by bjhargrave** [comment]
To run check_yaml, you must first make sure the schema submodule is present. So some more text is needed to talk about running git submodule update --init.

**Comment by jjasghar** [comment]
I think when you bring `git submodule update --init` into a conversation this is a bad idea for usability.

**Comment by lhawthorn** [comment]
As someone who has run into issues using the linter and would prefer to better understand why those issues were occurring and how I could avoid them, I am more in favor of temporarily bloating the documentation than keeping things obscure to the user. I could be convinced either way. As we all know, I have opinions and am perhaps overly fond of sharing them. :)

**Comment by bjhargrave** [comment]
I think we should have some text about using the check_yaml script even if it includes submodule commands. We just need to make it clearly stated that its use is optional.

**Pull request closed without merging**
