### PR TITLE
Add a skill to check if a passage is too ambiguous to support a claim

### PR DESCRIPTION
**Pull request by ae2015**
This is a re-submission of [**PR 668**](https://github.com/instructlab/taxonomy/pull/668).

**Describe the contribution to the taxonomy**

Given a text passage and a claim, determine if the passage is sufficient to conclude the claim. Here we are looking at passages that may be too ambiguous to support the claim, because they

- contain unresolved pronouns or pronoun phrases
- miss specific entity names or numerical values
- use phrases with too many possible interpretations
- use subjective language (rather than objective)

This skill is a prerequisite for the ability to generate grounded responses that are free from exaggerated or careless claims.

**Input given at the prompt**

In one example, we provide the following context to Merlinite 7b:
```
Passage:

What I saw today was the most wonderful and magnificent thing I have ever witnessed.

Claim:

Today's solar eclipse has made a strong impression on me.
```
Then we ask Merlinite 7b the following question:
```
Is Passage sufficient to conclude Claim?
```
Merlinite 7b wrongly answers "yes" and explains as follows:

**Response from the original model**

```
Yes, the passage is sufficient to conclude the claim. The speaker uses the words "wonderful" and
"magnificent" to describe what they saw today, which aligns with the experience of viewing a
solar eclipse. This strong impression suggests that the passage refers to the solar eclipse, making
the claim plausible.
```
So, for the current model, a suggested plausible interpretation is all it takes to conclude the claim. In other examples, the model tacitly substituted a pronoun in the passage with a specific entity name or let a numerical value stand without any grounding.

**Response from the fine-tuned model**

(did not have an opportunity to fine tune the model)

**Contribution checklist**

- [x] The contribution was tested with `ilab generate`
- [x] No errors or warnings were produced by `ilab generate`
- [x] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x] The `qna.yaml` file contains at least 5 `seed_examples`
- [x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [x] An `attribution.txt` file in the same folder as the `qna.yaml` file.

### CODE REVIEW

**Comment by RobotSail** [comment]
drop 1966cef feat(synthetic data): Add script to generate synthetic data readme (#650)
drop cc381ec Updating org name from instruct-lab to instructlab (#711)
pick 16cb720 Add ambiguity detection skill

**Comment by mingxzhao** [comment]
@instructlab-bot precheck

**Comment by mingxzhao** [comment]
@instructlab-bot generate

**Review by mingxzhao — APPROVED** [review]

**Comment by ae2015** [comment]
Hi @mingxzhao , I made the required formatting changes to `attribution.txt` and added the version line to `qna.yaml`. Can this PR be merged now? Thanks!

**Comment by jjasghar** [comment]
Sorry, no this is `e2e-ready` state. We need to the end to end run to see if it increases the model's performance before we can merge it. `e2e-ready` is on hold for the foreseeable future, but when @alinaryan comes back with the numbers when the next run happens we can look at merging if improvement.

**Comment by jjasghar** [comment]
Hi! 👋
It’s been a while since you’ve seen any movement on this PR. We haven’t forgotten about you!  We’ve run into some logistical issues, hence this delay. We absolutely want your PR, and being marketed as `e2e-ready` is still the last stop before we get it into the upstream model.

We are thankful for your patience and ask that you please keep this PR open. As soon as we finish all our behind-the-scenes work, we’ll test the full model against your submissions and, ideally, accept your amazing contribution(s)! 

Your Community Maintainer Team.

P.S. if you have any specific questions or thoughts, don’t hesitate to comment on pull request this or email [awesome@instructlab.ai](mailto:awesome@instructlab.ai) and [lhawthor@redhat.com](mailto:lhawthor@redhat.com), and we’ll get back to you as soon as possible.

**Comment by jjasghar** [comment]
Hi! 👋
Thank you for submitting this PR. We are ready to do some validation now, and we have a few candidates to see if they improve the model.
We some resources to run these release candidates, but we need _you_ to help us. Can you reach out to me either on Slack (@awesome) or email me at awesomeATinstructlab.ai so I can get you access via `ilab model chat`?
We can only run these models for a "week" or so, so please reach out as soon as possible and tell me which one is best for you on this PR.

**Pull request closed without merging**
