### PR TITLE
Black Capped (combined)

### PR DESCRIPTION
**Pull request by jjasghar**
This is the combined Black CappedPRs sfrom Red Hat Summit 2024.

This superseeds #873

### CODE REVIEW

**Comment by jjasghar** [comment]
@instructlab-bot precheck

**Comment by mingxzhao** [comment]
@instructlab-bot precheck

**Comment by mcorbin-ibm** [comment]
Per the new taxonomy (#1215 ), I recommend that this knowledge go here:

`knowledge/science/animals/birds/black_capped_chickadee`

**Comment by jjasghar** [comment]
Hi! 👋
Thank you for submitting this PR. We are ready to do some validation now, and we have a few candidates to see if they improve the model.
We some resources to run these release candidates, but we need _you_ to help us. Can you reach out to me either on Slack (@awesome) or email me at awesomeATinstructlab.ai so I can get you access via `ilab model chat`?
We can only run these models for a "week" or so, so please reach out as soon as possible and tell me which one is best for you on this PR.

**Comment by jjasghar** [comment]
After testing against the release candidate, this looks successful from the QnAs.

**Review by juliadenham — APPROVED** [review]
Looks good to me!

**Pull request merged**
