### PR TITLE
Inclusive IT terminology

### PR DESCRIPTION
**Pull request by nicholasjayantylearns**
**Made in collaboration with [shucshar](https://github.com/shucshar)**
Methodology: [Generative Design](https://www.researchgate.net/publication/242386653_Generative_Tools_for_Co-designing)

**Describe the contribution to the taxonomy**

What: A skill to flag non inclusive IT terminology usage and suggest inclusive IT terminology replacements.

Why: According to [McLean and Company’s HR Trends Report 2023](https://hr.mcleanco.com/research/ss/hr-trends-report-2023?initiate_downloads=false), DEI professionals report that the top challenge was lacking dedicated time to do dedicated DEI work (n=224 organizations reporting in, 59% indicated dedicated time was biggest challenge.)

84% of the reporting sample organizations indicate fostering a culture of belonging is one of the primary areas of influence their DEI org supports.  Additionally, 57% of respondents indicate they do not have a dedicated DEI team or staff at all.

Impact
The inclusive IT Language Skill is one example of what a DEI-driven Technology Roadmap could offer to help scale DEI influence while mitigating the risk of team burnout (39% of HR professionals indicate they experienced increased burnout in their roles, n=822).  

Possible areas of measurement:  
Reduce the # of tactical requests related to inclusion IT terminology guidance. 

Usage counts?

Experience goal: Enable end users to learn privately without putting belonging at risk.

**Input given at the prompt**

```
How might you replace the words in the following sentence to be more inclusive? 
A Ceph Monitor maintains the master copy of the Red Hat Ceph Storage cluster map
with the current state of the Red Hat Ceph Storage Cluster.
```

**Response from the original model**

```
To make the sentence more inclusive, consider replacing the terms "Ceph Monitor" 
and "Red Hat Ceph Storage Cluster" with more general terms that don't assume a specific gender or gender identity:    

* Replace "Ceph Monitor" with "cluster administrator" or "data storage manager."                                                                                                                         
* Replace "Red Hat Ceph Storage Cluster" with "data storage system" or "storage infrastructure."                                                                                                        

The revised sentence would look like this:   
A cluster administrator maintains the master copy of the data storage system
with the current state of the storage infrastructure.  
```

**Response from the fine-tuned model**

```
A cluster administrator maintains the primary copy of the data storage system with the current state of the storage infrastructure.  
```

**Contribution checklist**

- [X] The contribution was tested with `ilab generate`
- [X] No errors or warnings were produced by `ilab generate`
- [X] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [X] The `qna.yaml` file contains at least 5 `seed_examples`
- [X] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [X] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [X] Content does not include PII or otherwise sensitive or confidential information
- [X] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

### CODE REVIEW

**Comment by lhawthorn** [comment]
While I am grateful for all contributions to InstructLab, this one brings my heart joy. Thank you @nicholasjayantylearns!

**Comment by jjasghar** [comment]
@instructlab-bot precheck

**Comment by jjasghar** [comment]
@instructlab-bot generate

**Comment by jjasghar** [comment]
This seems to have worked _extremely_ well. Also spot checking the `generate` and all this looks great. Thank you for this, and this maybe one of the best examples we've had created so far.

**Comment by nicholasjayantylearns** [comment]
That is so awesome to hear! I've learned sooooo much! Thank you all for the
support!

Feedback is a gift and I'm open to any and all suggestions! And have tons
of ideas after going through one.   can't wait to continue contributing!

**Comment by ahmed-azraq** [comment]
This is a nice one, @nicholasjayantylearns !

**Comment by nicholasjayantylearns** [comment]
Thanks Ahmed!

Appreciate the feedback! Updated the PR to offer more context as well.

**Comment by nicholasjayantylearns** [comment]
@lhawthorn @jjasghar  - is there a step I need to take to address the Review Required step?

**Review by jjasghar — APPROVED** [review]
Approved, but we still need to do the end to end testing to see how it works with the upstream model.

**Comment by nicholasjayantylearns** [comment]
Ack! Thanks for the education and the reply!

**Comment by jjasghar** [comment]
Hi! 👋
It’s been a while since you’ve seen any movement on this PR. We haven’t forgotten about you!  We’ve run into some logistical issues, hence this delay. We absolutely want your PR, and being marketed as `e2e-ready` is still the last stop before we get it into the upstream model.

We are thankful for your patience and ask that you please keep this PR open. As soon as we finish all our behind-the-scenes work, we’ll test the full model against your submissions and, ideally, accept your amazing contribution(s)! 

Your Community Maintainer Team.

P.S. if you have any specific questions or thoughts, don’t hesitate to comment on pull request this or email [awesome@instructlab.ai](mailto:awesome@instructlab.ai) and [lhawthor@redhat.com](mailto:lhawthor@redhat.com), and we’ll get back to you as soon as possible.

**Comment by nicholasjayantylearns** [comment]
Thank you for the update! Let us know if there are any iterations we'd want
to deliver following the behind the scenes testing.

**Comment by nicholasjayantylearns** [comment]
Hello folks,

Just received a notification re: a stale Pr and auto close in 15 days. Any
steps I need to take?

Thank you!

**Comment by jjasghar** [comment]
Nope, it was caught by the stale bot before the update to the label. You're good :)

**Comment by bjhargrave** [comment]
I re-homed this contribution under the new taxonomy layout.

**Comment by nicholasjayantylearns** [comment]
Thanks for the update. When might we expect the new taxonomy to release with this merged?

**Comment by jjasghar** [comment]
Hi! 👋
Thank you for submitting this PR. We are ready to do some validation now, and we have a few candidates to see if they improve the model.
We some resources to run these release candidates, but we need _you_ to help us. Can you reach out to me either on Slack (@awesome) or email me at awesomeATinstructlab.ai so I can get you access via `ilab model chat`?
We can only run these models for a "week" or so, so please reach out as soon as possible and tell me which one is best for you on this PR.

**Comment by nicholasjayantylearns** [comment]
Test 1: Whitelist Terminology
`Help me use more inclusive IT Terminology in this sentence: All US companies are whitelisted.  

To make the IT terminology more inclusive, you can replace "whitelisted" with "trusted entities" or "allowed entities" to avoid any potential harm or misinterpretation. 

Here's the revised sentence: 
"All US companies that have satisfied the necessary security requirements are considered trusted or allowed entities within the IT ecosystem." This revised sentence promotes inclusivity by avoiding language that may be associated with negative connotations or exclusions.'

**Comment by nicholasjayantylearns** [comment]
Test 2: Blacklist Terminology
```
 How do I make this sentence use Inclusive IT Terminology: The organizations are blacklisted until further notice. 
```

Model response:
```
To make the IT terminology more inclusive, you can replace "blacklisted" with "blocked" or "denied access" to avoid any potential harm or misinterpretation. 

Here's the revised sentence: 
"The organizations are temporarily denied access until they fulfill the necessary security requirements to be re-added to the approved list, also known as a whitelist or allowed entities list."

This revised sentence promotes inclusivity by avoiding language that may be associated with negative connotations or exclusions.                                      
```

Conclusion: Test 2 Passed.

**Comment by nicholasjayantylearns** [comment]
Test 3: Master / Slave Terminology
```
Help me use Inclusive IT Terminology to enhance the following sentence: The master clock directs the slave clocks to maintain consistency.
```

Model response:
```
To make the IT terminology more inclusive, you can replace "master clock" with "primary clock" or "reference clock" and "slave clocks" with "replica clocks" or "allied clocks." 

Here's the revised sentence:         
"The primary clock directs the replica clocks to maintain synchronization." 

This revised sentence promotes inclusivity by avoiding language that may be associated with negative connotations or exclusions.      
```

Conclusion: Test 3 Passed

**Comment by ahmed-azraq** [comment]
Amazing, @nicholasjayantylearns 💯 😍

**Comment by poutinecurry** [comment]
Can you clarify how this contribution stays clear of the "Avoid these Topics" list, considering that it appears to address "hostile language", "insensitive ... comments", "discrimination", and/or "guard rails".

**Comment by bjhargrave** [comment]
> Can you clarify how this contribution stays clear of the "Avoid these Topics" list, considering that it appears to address "hostile language", "insensitive ... comments", "discrimination", and/or "guard rails".

Well it doesn't attempt to train the model to speak in hostile language, make insensitive comments, etc. It is a skill to reword sentences to be more inclusive. So I don't see a conflict with the avoid list.

**Comment by poutinecurry** [comment]
> Well it doesn't attempt to train the model to speak in hostile language, make insensitive comments, etc. It is a skill to reword sentences to be more inclusive. So I don't see a conflict with the avoid list.

The avoid list was phrased in terms of TOPIC, not a pro/con position within a topic.  If you now welcome telling models how to work with "complex social topics", may I suggest changing the SKILLS_GUIDE.md to say so.

**Comment by nicholasjayantylearns** [comment]
🙏🏽 thank you for the update!

**Comment by nicholasmakesthings** [comment]
If this PR got some kudos from another source - would it be appropriate to link here? 

[How Open Source can Democratize AI](https://www.ibm.com/think/podcasts/smart-talks/open-source-democratize-ai)

**Pull request merged**
