### PR TITLE
Softball QnA Knowledge

### PR DESCRIPTION
**Pull request by jjasghar**
Re-Re-adding softball PR: #659

### CODE REVIEW

**Comment by aakankshaduggal** [comment]
This PR is in the wrong folder- it needs to go in `knowledge/sports/.....`

**Comment by aakankshaduggal** [comment]
@jjasghar - Thanks for the PR, can you please change the location of your file - `knowledge/sports/overview/softball/qna.yaml`

**Comment by jjasghar** [comment]
Fixed.

**Comment by aakankshaduggal** [comment]
Thanks @jjasghar

**Comment by alinaryan** [comment]
Thank you for your submission. Here are your results: 
Your PR didn't change the model performance 
The model's new score is: 0.5108695652173914 
 The old score was: 0.5108695652173914 
||||||||||||||||||||||||||||||||||||||||||||||||||| 51.08695652173913%

**Comment by jjasghar** [comment]
Hi! :wave:
With the new update and release of 0.18.0, our [base knowledge submissions](https://github.com/instructlab/taxonomy/?tab=readme-ov-file#knowledge-yaml-examples) have drastically changed. This has given us an opportunity to significantly improve the accuracy of our fine-tuned models, which is a major win for our community!

But alas, that has caused some changes that this PR isn't able to continue forward. We greatly appreciate the work you've put into this, and wish we could accept it but the amount of work to get it to be `version: 3` is unrealistic for us to ask.
If you _do_ want to do this, please don't hesitate to take the `qna.yaml` update it, and build it out. Otherwise, we hope you come back to our community with a new submission and help build out our Open Source community-driven LLM.

If you have any questions directly, please don't hesitate to comment on the PR or email me at [awesomeATinstructlab.ai](http://awesomeatinstructlab.ai/) (yes, really), and I'll do my best to answer your questions.

**Pull request closed without merging**
