### PR TITLE
contributing knowledge submission for watsonx

### PR DESCRIPTION
**Pull request by kwright15**
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

- Some basic information about watsonx (based on the limited wikipedia info)
- Includes descriptions of watsonx.ai, watsonx.data, and watsonx.governance
- ...

**Input given at the prompt**

```
   What is watsonx.ai
```

**Response from the original model**

```
  WatsonX.AI is not a standard term in programming or artificial intelligence. I can provide some context on the terms used in your question:                  │
│                                                                                                                                                              │
│ - WatsonX: This could be a user interface (UI) library or framework for developing applications that use IBM's Watson AI services. It might include          │
│ pre-built components, APIs, or tools to help developers create visually appealing and interactive applications.                                              │
│ - AI: This stands for Artificial Intelligence, which refers to the simulation of human intelligence in machines that are programmed to think and learn.      │
│ These systems can analyze their own performance and improve from experience, making them useful for a wide range of applications, including language         │
│ processing, image recognition, and decision-making support.                                                                                                  │
│                                                                                                                                                              │
│ To clarify your question further, you could ask: "What is the WatsonX UI library or framework used for integrating AI services in my application?"  
```

**Response from the fine-tuned model**

I did not train the model, but I used ilab generate to generate 10 example Q&A pairs that looked good.

**Contribution checklist**

- [x] The contribution was tested with `ilab generate`
- [x] No errors or warnings were produced by `ilab generate`
- [x] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x] The `qna.yaml` file contains at least 5 `seed_examples`
- [x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both) **I did not prettify it because that would mess up the required formatting of the file**
- [x] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [x] Content does not include PII or otherwise sensitive or confidential information
- [x] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

### CODE REVIEW

**Comment by jjasghar** [comment]
https://github.com/instructlab/dev-docs/issues/59#issuecomment-2135852136 -- this needs to be resolved before anything farther.

**Comment by kwright15** [comment]
@jjasghar I did not use any information from ibm.com in my knowledge submission, only the limited data in wikipedia.

**Comment by jjasghar** [comment]
From our discussion in the triage meeting, @juliadenham mentioned that the original plan for the RH Summit was to add these to the model. But it seems it already knows about a bunch of these things. Let's run `precheck` against it and see if the model already knows about these topics.

**Comment by jjasghar** [comment]
@instructlab-bot precheck

**Comment by kwright15** [comment]
Interesting precheck results. It mentions Computer Vision for watsonx.ai but we withdrew those services from market a number of years ago. For watsonx.data it says it's a Python library (it's not.)

However, the prechecks I performed were using the default merlinite model, not granite. I need to understand if our PRs are contributing to merlinite, granite, or both?

**Comment by jjasghar** [comment]
>  I need to understand if our PRs are contributing to merlinite, granite, or both?

We've made some progress here. So when we put it into the "pipeline" with the end to end run, then both models are trained on this date. As of _now_ when you run `ilab train` you are only training locally the merlinte quantitized model on your local machine.

When we have our e2e run more "smooth" this is a reasonable thing to add into the pipeline, but we are still working out some stumbling blocks before we can more to the process.

Not to mention the legal aspect of this one also, we are still working on the legal side to get clearance on things.

Until we have clear direction from legal please put a PR with this domain in this: https://github.com/instructlab/dev-docs/blob/main/docs/knowledge-submissions-past-wikipedia.md

**Pull request closed without merging**
