### PR TITLE
Added knowledge: Nobel Laureates > India

### PR DESCRIPTION
**Pull request by sumanair**
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

-Added a 'Nobel Laureates' section
-Added a subsection called 'India'

**Input given at the prompt**

```
    Who won the Nobel Prize for Physics in 1930?
```

**Response from the original model**

```
    1930 Nobel Prize for Physics was awarded to Charles Thomson Rees Wilson for his invention of the cloud chamber, which made it possible to visualize and photograph ionizing particles. This invention significantly contributed to the understanding of atomic and subatomic particles.

```

**Response from the fine-tuned model**

```
   The Nobel Prize in Physics 1930 was awarded to Sir Chandrasekhara Venkata Raman "for his work on the scattering of light and for the discovery of the effect named after him."

[Explanation]
Sir Chandrasekhara Venkata Raman, an Indian physicist, was awarded the Nobel Prize in Physics in 1930 for his work on the scattering of light and for the discovery of the Raman effect. The Raman effect is a phenomenon in which the wavelength of light changes when it interacts with matter, leading to the observation of new frequencies of light called Raman lines. This discovery has had significant implications for various fields, including spectroscopy, remote sensing, and medical diagnostics.

In summary, Sir Chandrasekhara Venkata Raman was awarded the Nobel Prize in Physics in 1930 for his pioneering work on the scattering of light and the discovery of the Raman effect. This work has had a lasting impact on physics and related disciplines.

```

**Contribution checklist**

- [x] The contribution was tested with `ilab generate`
- [x] No errors or warnings were produced by `ilab generate`
- [x] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x] The `qna.yaml` file contains at least 5 `seed_examples`
- [x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [x] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [x] Content does not include PII or otherwise sensitive or confidential information
- [x] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

### CODE REVIEW

**Review by jjasghar — CHANGES_REQUESTED** [review]
Please fix the linting issues you see here: https://github.com/instructlab/taxonomy/pull/1148/files

**Comment by jjasghar** [comment]
@instructlab-bot precheck

**Comment by jjasghar** [comment]
Looks like `precheck` are just all wrong, so lets get this to generate to see if it builds up some good questions for us.

**Comment by jjasghar** [comment]
@instructlab-bot generate

**Comment by nerdalert** [comment]
@instructlab-bot generate

**Comment by nerdalert** [comment]
@instructlab-bot generate

**Comment by nerdalert** [comment]
@instructlab-bot generate

**Review by jjasghar — CHANGES_REQUESTED** [review]
Please fix the DCO issue(s).

**Comment by jjasghar** [comment]
Please fix the DCO issue.

**Comment by jjasghar** [comment]
I'm going to close this PR, i would reopen it with just the `qna.yaml` and `attribution.txt`.

**Comment by sumanair** [comment]
That's fair. https://github.com/instructlab/taxonomy/pull/1199 raised

**Comment by nerdalert** [comment]
@instructlab-bot generate

**Pull request closed without merging**
