### PR TITLE
information: Add skill to extract information from git commit headers

### PR DESCRIPTION
**Pull request by stefwalter**
**Describe the contribution to the taxonomy**

Here we add a sklil of parsing git commit headers such as those producted by the command ```git log``` 

**Input given at the prompt**

```
(venv) stef@dragon-thewalter-lan:~/src/instruct-lab-cli/instruct-lab$ lab chat
╭─────────────────────────────────── system ───────────────────────────────────╮
│ Welcome to Chat CLI w/ GGML-MERLINITE-7B-0302-Q4_K_M (type /h for help)      │
╰──────────────────────────────────────────────────────────────────────────────╯
>>> Given the commit:                                               [S][default]
 
"
commit b14caac3effb5d78d6f884345da701b4b4a78386
Author: Marko Lukša <blah@redhat.com>
Date:   Tue Mar 5 11:15:21 2024 +0100
 
    Improve rendering of examples in README (#54)
 
    Signed-off-by: Marko Lukša <mluksa@redhat.com>
"
 
what is the author's email address?
```
**Response that was received**

```
╭─────────────────────── ggml-merlinite-7b-0302-Q4_K_M ────────────────────────╮
│ The author's email address is mluksa@redhat.com, as mentioned in the commit  │
│ message.                                                                     │
╰────────────────────────────────────────────────────── elapsed 2.810 seconds ─╯
>>>                                                                 [S][default]
```

**Response that is now received instead, after ```lab generate``` and ```lab train``` and serving the new model**
```
>>> Given the commit:                                               [S][default]
 
 
"
commit b14caac3effb5d78d6f884345da701b4b4a78386
Author: Marko Lukša <blah@redhat.com>
Date:   Tue Mar 5 11:15:21 2024 +0100
 
    Improve rendering of examples in README (#54)
 
    Signed-off-by: Marko Lukša <mluksa@redhat.com>
"
 
what is the author's email address?
╭─────────────────────── ggml-merlinite-7b-0302-Q4_K_M ────────────────────────╮
│ The author's email address is blah@redhat.com, as stated in the commit       │
│ message.                                                                     │
╰────────────────────────────────────────────────────── elapsed 7.583 seconds ─╯
```

**Please, confirm that you have tested your contribution with `lab generate` and ensured that it does not produce any warnings or errors:**

Yes. No errors

```
(venv) $ lab generate
INFO 2024-03-06 15:23:35,175 lab.py:263 Generating model 'ggml-merlinite-7b-0302-Q4_K_M' using 10 cpus, taxonomy: '/data/src/instruct-lab-taxonomy' and seed 'seed_tasks.json'
  0%|                                                                                  | 0/100 [00:00<?, ?it/s]Cannot find prompt.txt. Using default prompt.
109it [1:12:11, 23.38s/it]INFO 2024-03-06 16:35:46,543 generate_data.py:434 Generation took 4331.37s           
110it [1:12:11, 39.38s/it]
```

### CODE REVIEW

**Review by bjhargrave — CHANGES_REQUESTED** [review]
To improve this, you may want to use different "people" for each of the roles: Commit, Author, Signed-off-by to help in learning which part of the context contains the requested information. Using the same person for each role does not make it clear where in the context the requested information comes from.

**Review by bjhargrave — CHANGES_REQUESTED** [review]
Small correction.

**Review by bjhargrave — APPROVED** [review]

**Review by bjhargrave — CHANGES_REQUESTED** [review]
It was requested that you update this contribution to have a diversity of names and email addresses (all fictitious to avoid PII) in the examples. That is, don't reuse a name or an email address. This will help so the generated data does not have deep repetition of the same names and emails thus causing the model to learn them rather than learn about the extraction site. Basically it would be best if each example context was distinct from all other example's contexts.

You will also need to have at least 5 examples now (updated requirement), but more is even better.

Thanks!

**Review by jjasghar — APPROVED** [review]
This looks like a great addition

**Comment by n1hility** [comment]
Thank you for your contribution to InstructLab! Unfortunately, once a Github repo is made public, all open PRs are automatically closed since they link against a private repo. We have detected that your PR might have been one of the ones affected by this change. If you are still interested in contributing your improvement, please fill out the following short form by no later than May 3rd, and we will get back to you with the additional steps necessary once we have had time to assess the PRs of those still interested:

https://forms.gle/V7SrPPMZDo6iGDYu8

**Pull request closed without merging**
