### PR TITLE
Skill to draw a simple ASCII art watch

### PR DESCRIPTION
**Pull request by davidhildenbrand**
**Describe the contribution to the taxonomy**

Provide a simple skill that can draw an ASCII (wrist) watch. Apparently, other AI models can do a better job ;)

**Input given at the prompt**

```
 Draw a watch displaying the time 1:59.
```

**Response that was received**

```
 ╭────────────────────────────────────────── ggml-merlinite-7b-0302-Q4_K_M ──────────────────────────────────────────╮
│ Certainly! Here's a watch displaying the time 1:59:                                                               │
│                                                                                                                   │
│ [Watch Face]                                                                                                      │
│ Hands:                                                                                                            │
│ - Seconds hand: Pointing to the 9 marker on the dial.                                                             │
│ - Minutes hand: Pointing to the 12 marker on the dial.                                                            │
│ - Hours hand: Pointing to the 1 marker on the dial.                                                               │
│ Dial:                                                                                                             │
│ - A standard clock face with 12 markers (1, 2, 3, etc.) around the circumference.                                 │
│ - The minute and hour hands are located between the 12 and 1 markers, while the seconds hand is pointing to the 9 │
│ marker.                                                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────── elapsed 21.015 seconds ─╯
```
In some other cases it would try drawing ASCII art, but fail miserably.

**Response that is now received instead**

Do not have trained model yet to test it. This is my expectation:

```
      |=|
     _|=|_
    /  -  \
   { 01:59 }=
    \__-__/
      |=|
      |=|
```

**Contribution checklist**

- [x] tested contribution with `lab generate`
- [x] `lab generate` does not produce any warnings or errors
- [x] all [commits are signed off](https://github.com/instruct-lab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x] the `qna.yaml` file was [linted](https://yamllint.com)

### CODE REVIEW

**Review by bjhargrave — CHANGES_REQUESTED** [review]

**Comment by davidhildenbrand** [comment]
@jjasghar just wondering, why closed?

**Comment by jjasghar** [comment]
this is how to Refork (fix) your PR for taxonomy and resubmit: https://youtu.be/x6NfWvrkjnI it seems we ran into a problem with the private to public conversion.

**Comment by n1hility** [comment]
Thank you for your contribution to InstructLab! Unfortunately, once a Github repo is made public, all open PRs are automatically closed since they link against a private repo. We have detected that your PR might have been one of the ones affected by this change. If you are still interested in contributing your improvement, please fill out the following short form by no later than May 3rd, and we will get back to you with the additional steps necessary once we have had time to assess the PRs of those still interested:

https://forms.gle/V7SrPPMZDo6iGDYu8

**Comment by davidhildenbrand** [comment]
@jjasghar @n1hility thanks for the info. As my MR did not get any attention for almost one month, I won't create another one that will be ignored. Thanks.

**Pull request closed without merging**
