### PR TITLE
Add skill to replace words in text with corresponding emoji

### PR DESCRIPTION
**Pull request by Mohit-Gaur**
Re-submitting PR #303 

**Describe the contribution to the taxonomy**

Added a new skill to replace words in text with their corresponding emoji

**Input given at the prompt**

```
Replace words with emoji in this text: I had a pizza for dinner last night
```

**Response from the original model**

```
I 🍕 had 🍴 a 🍕 pizza 🍕 for 🍴 dinner 🍴 last night 🌙
```

**Response from the fine-tuned model**

```
I had a 🍕 for dinner last night 🌃
```
---
**Prompt 2 - Testing the fine-tuned model with a new example**

```
Replace words with emoji in this text: I'm going to the movies tonight, I can't wait to see the new superhero film!
```

**Response that was received**

```
I'm 🎬 going to the 🍿movies tonight, I can't 😱 wait to see the new superhero 🎥film!
```

**Response that is now received instead**

```
I'm going to the 🎥 tonight, I can't wait to see the new 🦸‍♀️🦸‍♂️ film!
```

**Contribution checklist**

- [x] The contribution was tested with `ilab generate`
- [x] No errors or warnings were produced by `ilab generate`
- [x] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x] The `qna.yaml` file contains at least 5 `seed_examples`
- [x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [x] An `attribution.txt` file in the same folder as the `qna.yaml` file.

### CODE REVIEW

**Comment by jjasghar** [comment]
@instructlab-bot precheck

**Comment by RobotSail** [comment]
You can fix your PR with `git rebase -i upstream/main`  and then set the commands to

```
drop 1966cef feat(synthetic data): Add script to generate synthetic data readme (#650)
drop cc381ec Updating org name from instruct-lab to instructlab (#711)
pick 0bf1f70 Add skill for creating tables in Asciidoc format
pick eb45529 Use attribution.txt instead of inline
```

**Review by jjasghar — APPROVED** [review]

**Comment by alinaryan** [comment]
Thank you for your submission. Here are your results: 
Your PR decreased the model performance by 0.27499999999999947 points. 
The model's new score is: 4.508333333333334 
 The old score was: 4.783333333333333 
||||||||||||||||||||||||||||||||||||||||||||| 45.083333333333336%

**Comment by alinaryan** [comment]
Thank you for your submission. Here are your results: 
Your PR improved the model performance by 0.18333333333333357 points. 
The model's new score is: 6.483333333333333 
 The old score was: 6.3 
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 64.83333333333333%

**Pull request merged**
