### PR TITLE
Adding new skill - technical or scientific based poetry (haikus)

### PR DESCRIPTION
**Pull request by hms20112015**
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

- This contribution provides examples of haikus written specifically about data science and computing. The model was trained on a based qna.yml file along with synthetic data and now provides better output related to formulating or developing a haiku about the above topics (data science, analytics and computing).

**Input given at the prompt**

"Tell me a haiku about data science."

**Response from the original model**

`Data crunches, algorithms thrive,
Unveiling secrets in the night,
Discovery's the prize.`

**Response from the fine-tuned model**

`Algorithms slice through bytes,
Revealing truths in numbers' guise,
Insights born in silence.`

**Contribution checklist**

- [X ] The contribution was tested with `ilab generate`
- [ X] No errors or warnings were produced by `ilab generate`
- [ X] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [ X] The `qna.yaml` file contains at least 5 `seed_examples`
- [ X] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [ X] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [ X] Content does not include PII or otherwise sensitive or confidential information
- [ X] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

### CODE REVIEW

**Comment by jjasghar** [comment]
I'm sorry, it looks like you submitted this to the wrong repository. This should be the internal one for the event you are working on. This is the upstream taxonomy directory.

**Comment by hms20112015** [comment]
@jjasghar Thank you @jjasghar! I will review this and resubmit. Appreciate the quick response!

**Comment by hms20112015** [comment]
@jjasghar Hi JJ, 
Pardon my confusion, is there another public taxonomy repository? 
I am not working on a specific event, my intention was to contribute a qna.yml file to the public taxonomy repo.

**Comment by jjasghar** [comment]
If this wasn't part of the Watsonx challenge, I apologize, it seemed that it was.

For this submission, we don't accept poetry anymore, per our policies:

Thank you for taking the time to submit to instructlab! I know this wasn't easy and could have been quite time-consuming. Unfortunately, our team has decided that submissions for jokes or poems (skills and knowledge) are no longer supported or approved. We received so many at the beginning, and with jokes being "in the eye of the beholder" and puns requiring nuance for native English speakers, we realized we were possibly unconsciously biasing our model. We have discovered that working with both topics has its own challenges, and if we want something generalized, finding consensus was unsuccessful. 

We have updated the [avoid topics](https://github.com/instructlab/community/tree/main/docs#avoid-these-topics) to reflect this, and if you have more questions, don't hesitate to comment on this PR. We may revisit this in the future, but we are looking for unique skills or new knowledge for the model; poems and jokes, unfortunately, don't fit this plan. 

Thank you again for taking this time, and we are looking forward to your next PR to the instructlab project!

**Comment by hms20112015** [comment]
@jjasghar Hey JJ! Thank you again for the quick response. 

No, I am not affiliated with the WatsonX challenge. I will check out the list of topics to avoid, the link above takes me to the docs page for InstructLab.

It sounds like haikus aare no longer accepted under freeform composition but the following might be:

Sourced from [here](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md):

"Accepted Skills
Creative Writing / Poetics
Adding new types of documents and writing styles to the LLM are welcome. Consider:

Song lyrics
Soliloquies
Five paragraph essays
Arguments"

Is that your understanding as well?

**Comment by jjasghar** [comment]
I strongly suggest not doing anything related to poems or the like. The triage team will not accept them due to the lower value they add to the project, and only very particular situations can upstream them.

**Pull request closed without merging**
