### PR TITLE
Knowledge: IBM Granite Knowledge

### PR DESCRIPTION
**Pull request by ahmed-azraq**
Knowledge contribution about the IBM Granite model

Edit -- Created through InstructLab UI

**Input given at the prompt**

What is IBM Granite?

**Response from the original model**
image

```
IBM Granite is a secure, scalable, and flexible infrastructure solution designed to help organizations build, deploy, and manage applications and services in a hybrid cloud environment. It provides a wide range of features and benefits, including:

1. **Consistent Management:** IBM Granite enables consistent management of your infrastructure across public, private, and hybrid cloud environments, making it easier to manage your applications and services.
2. **Scalability:** IBM Granite offers unlimited scalability, allowing you to quickly and easily scale your infrastructure up or down as needed to meet your changing business needs.
3. **Security:** IBM Granite provides robust security features, including encryption, access controls, and intrusion detection, to help protect your applications and data.
4. **Flexibility:** IBM Granite supports a wide range of operating systems, applications, and databases, making it a flexible solution for your organization.
5. **Cost-Effective:** IBM Granite is a cost-effective solution, as it eliminates the need for you to invest in and manage your own infrastructure.

IBM Granite is a powerful and versatile infrastructure solution that can help your organization to improve efficiency, reduce costs, and increase agility. If you have any specific questions about IBM Granite or how it can benefit your organization, feel free to ask!`
```

**Response from the fine-tuned model**

```
╭───────────────────────── instructlab-granite-7b-lab-Q4_K_M.gguf ──────────────────────────╮
│ IBM Granite is an open-source foundation model developed by IBM Research, specifically    │
│ designed for conversational AI tasks. It is built on the basis of the Granite-7b-base     │
│ language model and is intended to be a versatile and adaptable platform for various       │
│ applications in the realm of artificial intelligence.                                     │
│                                                                                           │
│ The primary goal of IBM Granite is to engage in meaningful conversations with users,      │
│ providing accurate and contextually relevant responses. It has been pre-trained on an     │
│ extensive dataset, allowing it to understand and respond to a wide array of topics and    │
│ questions.                                                                                │
│                                                                                           │
│ Moreover, IBM Granite is designed to be a highly customizable model, enabling developers  │
│ to fine-tune it for specific use cases. By leveraging the power of fine-tuning, users can │
│ tailor the model's performance to meet their unique requirements, ensuring optimal        │
│ results in various scenarios.                                                             │
│                                                                                           │
│ In summary, IBM Granite is an advanced AI language model that combines the strengths of   │
│ open-source foundation models with customization capabilities, making it a powerful tool  │
│ for a wide range of conversational AI applications.                                       │
│                                                                                           │
│ If you have any specific questions about IBM Granite or would like to know more about its │
│ features and functionalities, please feel free to ask!                                    │
╰─────────────────────────────────────────────────────────────────── elapsed 5.782 seconds ─╯
```

**Contribution checklist**

- [x] The contribution was tested with `ilab generate`
- [x] No errors or warnings were produced by `ilab generate`
- [x] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x] The `qna.yaml` file contains at least 5 `seed_examples`
- [x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [x] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [x] Content does not include PII or otherwise sensitive or confidential information
- [x] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

### CODE REVIEW

**Comment by jjasghar** [comment]
Hi! Until we have our community model builds back up and running, many PRs will be held off. We are hoping to have them running again soon, and if you have any specific questions don't hesitate to comment here or reach out to #triage in slack.

**Comment by ahmed-azraq** [comment]
@bjhargrave @jjasghar @joesepi

**Comment by mcorbin-ibm** [comment]
@jjasghar This PR was likely created in the authoring/building of @ahmed-azraq 's tutorial on using InstructLab UI to contribute knowledge:  https://developer.ibm.com/tutorials/awb-contributing-llm-granite-instructlab-ui/.  In fact, he links to this PR in the final step.

**Comment by jjasghar** [comment]
We are not accepting the IBM Granite PRs at the moment. We have been overrun with submissions and need to figure out which one to accept.

**Pull request closed without merging**
