### PR TITLE
Lapis Lazuli

### PR DESCRIPTION
**Pull request by wkulhanek**
**Describe the contribution to the taxonomy**

Issue 836. Lapis Lazuli.

### CODE REVIEW

**Comment by jjasghar** [comment]
@wkulhanek thank you! Can you change your file name from `.txt` to `.yaml`? If not, I can make some edits if you're ok with it.

**Comment by wkulhanek** [comment]
Done. Thanks for catching that @jjasghar !

**Comment by jjasghar** [comment]
@wkulhanek thanks for this! Can you squash this down to one commit?

**Comment by jjasghar** [comment]
Please fix the linting issues too.

**Pull request closed without merging**
