### PR TITLE
Ignore: bot testing

### PR DESCRIPTION
**Pull request by vishnoianil**
This skill was inspired by one of the tests included in mt-bench. It included some questions that the model answered incorrectly. When given the same question manually, I got the following incorrect answer:

> Q: David has three sisters. Each of them has one brother. How many
>    brothers does David have?
> A: David has three sisters, and each of them has one brother, so it
>    must be the same brother in all cases. Therefore, David has 1 brother.

If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

- ...
- ...
- ...

**Input given at the prompt**

```
   ...
```

**Response from the original model**

```
  ...
```

**Response from the fine-tuned model**

```
  ...
```

**Contribution checklist**

- [ ] The contribution was tested with `ilab generate`
- [ ] No errors or warnings were produced by `ilab generate`
- [ ] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [ ] The `qna.yaml` file contains at least 5 `seed_examples`
- [ ] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [ ] An `attribution.txt` file in the same folder as the `qna.yaml` file.

### CODE REVIEW

**Comment by vishnoianil** [comment]
@instruct-lab-bot help

**Comment by vishnoianil** [comment]
@instructlab-bot precheck

**Comment by vishnoianil** [comment]
@instructlab-bot precheck

**Comment by vishnoianil** [comment]
@instructlab-bot precheck

**Comment by vishnoianil** [comment]
@instructlab-bot precheck

**Comment by vishnoianil** [comment]
@instructlab-bot precheck

**Comment by vishnoianil** [comment]
@instructlab-bot precheck

**Comment by vishnoianil** [comment]
@instructlab-bot precheck

**Comment by vishnoianil** [comment]
@instructlab-bot precheck

**Comment by vishnoianil** [comment]
@instructlab-bot precheck

**Comment by RobotSail** [comment]
You can fix this PR with `git rebase -i upstream/main` and set the commands to:

```
drop 1966cef feat(synthetic data): Add script to generate synthetic data readme (#650)
pick ad41a8c skill: Add reasoning skill about siblings
```

Then when you have a merge conflict, you'll want to change it from:
```
<<<<<<< HEAD
# InstructLab 🐶 Taxonomy

=======
# InstructLab 🥼 Taxonomy
>>>>>>> ad41a8c (skill: Add reasoning skill about siblings)
```
to:

``
# InstructLab 🐶 Taxonomy

```

**Pull request closed without merging**
