### PR TITLE
DOCS: Adding details for new knowledge methods and attribution text

### PR DESCRIPTION
**Pull request by kelbrown20**
**Description:** 
- Adds new knowledge guidelines
- Adds new skills guidelines 

Preview: 
https://github.com/kelbrown20/kelly-taxonomy/tree/new-knowledge-updates

### CODE REVIEW

**Review by lehors — APPROVED** [review]
LGTM. Generally speaking, we should adopt a more incremental approach with smaller PRs that can be more easily reviewed and merged as we make progress rather than delay and have a large PR which is more likely to create conflicts.
In this case it would have made sense to have 2 separate PRs: knoweldge and attribution.
But so I'm totally in favor of merging this as is and follow up with additional PRs if needed.
Thanks!

**Review by juliadenham — APPROVED** [review]
LGTM

**Review by bjhargrave — CHANGES_REQUESTED** [review]
Thanks for the update! I have some suggested changes.

**Review by bjhargrave — APPROVED** [review]
This looks great. Just a couple of nits but we can fix in a followup PR.

**Pull request merged**
