### PR TITLE
Ask clarifying question to understand context skill.

### PR DESCRIPTION
**Pull request by ascerra**
Re-adding Ask clarifying question to understand context skill PR #294

### CODE REVIEW

**Comment by mingxzhao** [comment]
@instructlab-bot precheck

**Comment by mingxzhao** [comment]
@instructlab-bot generate

**Comment by mingxzhao** [comment]
It seems that the teacher model does not currently have the capability to generate quality synthetic data for this skill. This will be closed for now. If we make changes to the teacher model please feel free to resubmit for testing again!

**Review by mingxzhao — COMMENTED** [review]
need attribution.txt

**Comment by ascerra** [comment]
> It seems that the teacher model does not currently have the capability to generate quality synthetic data for this skill. This will be closed for now. If we make changes to the teacher model please feel free to resubmit for testing again!

Is that based on the qarating values [here](https://instruct-lab-bot.s3.us-east-2.amazonaws.com/sdg-svc-pr-851-4811b7902bca1490267c7105f804d2a13b13618b/sdg_1715354116_qna.yaml.json-viewer.html)?

**Comment by mingxzhao** [comment]
No so much the qa ratings but the "inputs" field. This is the field that contains the generated questions from the synthetic data generator. As you can see, it seems fairly confused and generates the clarifying question as the questions.

**Comment by ascerra** [comment]
Ok so based on the icl_q and icl_a we try to generate inputs (questions) and targets (answers) that are similar to what I've submitted?

I'm curious what a successful "inputs" value would be for something like this?

**Pull request closed without merging**
