### PR TITLE
Oscars 2024 results

### PR DESCRIPTION
**Pull request by juliadenham**
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

- ... The results of the 2024 Oscars.
- ... Performers at the 2024 Oscars.
- ... Information about the award show.

**Input given at the prompt**

```
   ...
```

**Response from the original model**

```
  ...
```

**Response from the fine-tuned model**

```
  ...
```

**Contribution checklist**

- [ ] The contribution was tested with `lab generate`
- [ ] No errors or warnings were produced by `lab generate`
- [x] All [commits are signed off](https://github.com/instruct-lab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x] The `qna.yaml` file contains at least 5 `seed_examples`
- [x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)

### CODE REVIEW

**Review by mingxzhao — CHANGES_REQUESTED** [review]

**Comment by jjasghar** [comment]
I mean... is .03 a good move up? how do we know it's not on a scale of 1000x 🤷

**Comment by n1hility** [comment]
Thank you for your contribution to InstructLab! Unfortunately, once a Github repo is made public, all open PRs are automatically closed since they link against a private repo. We have detected that your PR might have been one of the ones affected by this change. If you are still interested in contributing your improvement, please fill out the following short form by no later than May 3rd, and we will get back to you with the additional steps necessary once we have had time to assess the PRs of those still interested:

https://forms.gle/V7SrPPMZDo6iGDYu8

**Comment by alinaryan** [comment]
Thank you for your submission. Here are your results: 
Your PR decreased the model performance by 0.15000000000000002 points. 
The model's new score is: 0.3 
 The old score was: 0.45 
|||||||||||||||||||||||||||||| 30.0%

**Comment by alinaryan** [comment]
Thank you for your submission. Here are your results: 
Your PR decreased the model performance by 0.050000000000000044 points. 
The model's new score is: 0.76 
 The old score was: 0.81 
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 76.0%

**Pull request closed without merging**
