### PR TITLE
Add shopping based on recipes

### PR DESCRIPTION
**Pull request by lhellebr**
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

Makes a shopping list for you based on what the recipe calls for and what you already have.
Result => Now it's slightly more talkative but correct.

**Input given at the prompt**

```
I'm making pizza. I need flour, water, salt, yeast, tomato puree, mozzarella and basil. I have flour, water, to
mato puree and basil. What do I need to buy?
```

**Response that was received**

```
Based on the ingredients you currently have available and the toppings you mentioned, you will need to purchase
the following:

1. Yeast: This is the leavening agent that will help the dough rise, giving your pizza a light and airy
texture.
2. Salt: A small amount of salt can enhance the flavor of the dough, so it is recommended to use it in your
pizza recipe.
3. Mozzarella cheese: This is the classic cheese choice for pizzas, adding a creamy and mild flavor to the 
dish. 
4. Fresh basil: A popular garnish for pizzas, basil can add a fresh and aromatic touch to your homemade pizza. 

By adding these missing ingredients to your shopping list, you will be able to make your desired pizza with all
the necessary components.
```

**Response that is now received instead**

```
To make pizza, you will need to buy the following ingredients:
1. Fresh or active dry yeast
2. Salt
3. Mozzarella cheese

By having these additional items, you can prepare the dough and assemble your pizza with the provided
ingredients (flour, water, tomato puree, and basil). The yeast is essential for the rising process of the
dough, while the salt enhances the flavor of the dough. Mozzarella cheese is a classic choice for pizza
toppings, but feel free to experiment with other cheeses or ingredients to suit your taste preferences.

To ensure the best results, consider the following tips:
1. For the dough, use bread flour or a high-protein all-purpose flour for better texture and elasticity.
2. Activate the yeast in warm water (around 110°F or 45°C) with a pinch of sugar to help it grow. 
3. Knead the dough for 10-15 minutes to develop the gluten, which will result in a chewy crust.
4. Proof the dough in a warm place for at least 1-2 hours or up to 24 hours for a more flavorful crust.
5. Stretch or roll out the dough to your desired thickness and shape.
6. Pre-bake the crust for a few minutes before adding the toppings to prevent a soggy crust.
7. Bake the pizza at high temperatures (around 475°F or 245°C) for a crispy crust.
8. Feel free to experiment with various toppings, sauces, and cheese varieties to create your unique pizza
style.                                                                                                          │
9. Garnish with fresh basil leaves and enjoy your homemade pizza!
```

**Contribution checklist**

- [x] Contribution was tested with `lab generate`
- [x] No errors or warnings were produced by `lab generate`
- [x] All [commits are signed off](https://github.com/instruct-lab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)

### CODE REVIEW

**Comment by n1hility** [comment]
Thank you for your contribution to InstructLab! Unfortunately, once a Github repo is made public, all open PRs are automatically closed since they link against a private repo. We have detected that your PR might have been one of the ones affected by this change. If you are still interested in contributing your improvement, please fill out the following short form by no later than May 3rd, and we will get back to you with the additional steps necessary once we have had time to assess the PRs of those still interested:

https://forms.gle/V7SrPPMZDo6iGDYu8

**Comment by lhellebr** [comment]
I completed all the required extra steps a month ago! Do i really need to go through this additional process? This whole situation is not my fault.

**Comment by jjasghar** [comment]
@lhellebr this is how to Refork (fix) your PR for taxonomy and resubmit: https://youtu.be/x6NfWvrkjnI it seems we ran into a problem with the private to public conversion. You can skip the form in this situation.

**Comment by lhellebr** [comment]
@jjasghar Thanks, I re-added my PR

**Pull request closed without merging**
