### PR TITLE
kebab case

### PR DESCRIPTION
**Pull request by matteopulcini6**
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

Allows the model to replace kebab case.

**Input given at the prompt**

```
Convert this to Kebab Case: numberOfDonuts
```

**Response from the original model**

```
  numberOfDonuts
```

**Response from the fine-tuned model**

```
 number-of-donuts
```

**Contribution checklist**

- [ x] The contribution was tested with `ilab generate`
- [ x] No errors or warnings were produced by `ilab generate`
- [ x] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x ] The `qna.yaml` file contains at least 5 `seed_examples`
- [ x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [ x] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [ x] Content does not include PII or otherwise sensitive or confidential information
- [ x] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

### CODE REVIEW

**Comment by jjasghar** [comment]
Please fix the DCO :)

**Comment by jjasghar** [comment]
Please fix the linting issue(s).

**Comment by jjasghar** [comment]
@instructlab-bot precheck

**Comment by jjasghar** [comment]
Looking at the `precheck` it seems the model already does this quite well. 

@mingxzhao or @bjhargrave can you confirm?

**Comment by bjhargrave** [comment]
> can you confirm?

Yes, it looks good to me also. The last question was this properly responded to, but I think the question could be better written. "Convert this" is a bit vague. "Convert the following text:" would be more precise.

But I think we can close this PR as the model is already good at the skill.

**Comment by bjhargrave** [comment]
Closing since the merlinite-7b model is already good at this skill. 

Thank you for your contribution!

**Pull request closed without merging**
