### PR TITLE
Adds Tabby Cat knowledge

### PR DESCRIPTION
**Pull request by jregehr**
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

https://github.com/instructlab/taxonomy/issues/798

**Adding Tabby Cat knowledge to the taxonomy**

- What is a Tabby cat
- What is an Orange Tabby cat
- Popular "Oramge" meme
- Tabby cat markings

Signed-off-by: Jonathan Regehr <jonathan217@gmail.com>

**Contribution checklist**

- [x] The contribution was tested with `ilab generate`
- [x] No errors or warnings were produced by `ilab generate`
- [x] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x] The `qna.yaml` file contains at least 5 `seed_examples`
- [x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [x] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [x] Content does not include PII or otherwise sensitive or confidential information
- [x] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

### CODE REVIEW

**Comment by jjasghar** [comment]
Can you remove the `.gitignore` file and fix the DCO check please?

**Comment by jregehr** [comment]
> Can you remove the `.gitignore` file and fix the DCO check please?

@jjasghar There actually isn't a `.gitignore` in the `knowledge/animals/tabby_cat` directory. Fixed the DCO check.

**Comment by jjasghar** [comment]
Can you fix the DCO issue? Thanks!

**Comment by jregehr** [comment]
@instructlab-bot precheck

**Pull request closed without merging**
