### PR TITLE
Skill:List specific number synonyms for one word

### PR DESCRIPTION
**Pull request by yanpliu**
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

- ... List specific number synonyms for one word
- ... List one synonyms for one word
- ...List two synonyms for one word
- ... List three synonyms for one word

**Input given at the prompt**

```
(instructlab_vv) [root@dell-r640-041 synonyms]#  ilab generate --num-instructions 10
llama_cpp_python is built without hardware acceleration. ilab generate will be very slow.
Generating synthetic data using 'merlinite-7b-lab-Q4_K_M' model, taxonomy:'/home/instructlab/taxonomy' against http://127.0.0.1:8000/v1 server
INFO 2024-05-26 22:36:58,186 generate_data.py:468 Selected taxonomy path compositional_skills->general->synonyms
Q> What is an antonym to the word ‘attend’? Please list and separate with newline.
I> 
A> An antonym to Attend is not attend.

 10%|████████▌                                                                            | 1/10 [00:20<03:05, 20.58s/it]INFO 2024-05-26 22:37:18,766 generate_data.py:468 Selected taxonomy path compositional_skills->general->synonyms
INFO 2024-05-26 22:37:38,998 generate_data.py:468 Selected taxonomy path compositional_skills->general->synonyms
INFO 2024-05-26 22:37:44,410 generate_data.py:468 Selected taxonomy path compositional_skills->general->synonyms
INFO 2024-05-26 22:38:42,586 generate_data.py:468 Selected taxonomy path compositional_skills->general->synonyms
INFO 2024-05-26 22:38:55,369 generate_data.py:468 Selected taxonomy path compositional_skills->general->synonyms
Q> Please list and separate with newline some alternative words to describe the word 'attend' that are used when a person is participating in an event or a gathering.
I> 
A> Alternative words to describe 'Attend' are:
Participate in
Take part in
Show up at
Be present at
Join in
Take part in
Contribute to
Make an appearance at
Turn up for
Come to

 30%|█████████████████████████▌                                                           | 3/10 [02:33<06:22,

 50%|██████████████████████████████████████████▌                                          | 

 60%|███████████████████████████████████████████████████                                  
 90%|████████████████████████████████████████████████████████████████████████████▌        | 9/10 [07:32<00:48, 48.13s/it]INFO 2024-05-26 22:44:30,664 generate_data.py:468 Selected taxonomy path compositional_skills->general->synonyms
INFO 2024-05-26 22:44:52,830 generate_data.py:468 Selected taxonomy path compositional_skills->general->synonyms
INFO 2024-05-26 22:45:40,164 generate_data.py:468 Selected taxonomy path compositional_skills->general->synonyms
INFO 2024-05-26 22:45:51,975 generate_data.py:468 Selected taxonomy path compositional_skills->general->synonyms
INFO 2024-05-26 22:45:58,184 generate_data.py:468 Selected taxonomy path compositional_skills->general->synonyms
INFO 2024-05-26 22:46:21,326 generate_data.py:468 Selected taxonomy path compositional_skills->general->synonyms
INFO 2024-05-26 22:46:46,113 generate_data.py:468 Selected taxonomy path compositional_skills->general->synonyms
```
```
(instructlab_vv) [root@dell-r640-041 synonyms]# ilab train
INFO 2024-05-26 22:48:53,726 config.py:58 PyTorch version 2.3.0 available.
LINUX_TRAIN.PY: NUM EPOCHS IS:  1
LINUX_TRAIN.PY: TRAIN FILE IS:  generated/train_merlinite-7b-lab-Q4_K_M_2024-05-26T22_36_58.jsonl
LINUX_TRAIN.PY: TEST FILE IS:  generated/test_merlinite-7b-lab-Q4_K_M_2024-05-26T22_36_58.jsonl
LINUX_TRAIN.PY: Using device 'cpu'
LINUX_TRAIN.PY: LOADING DATASETS
Generating train split: 11 examples [00:00, 3144.80 examples/s]
Generating train split: 4 examples [00:00, 1685.64 examples/s]
/home/env/instructlabenv/instructlab_vv/lib/python3.12/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
tokenizer_config.json: 100%|████████████████████████████████████████████████████████| 2.33k/2.33k [00:00<00:00, 23.2MB/s]
tokenizer.model: 100%|████████████████████████████████████████████████████████████████| 493k/493k [00:00<00:00, 9.62MB/s]
tokenizer.json: 100%|███████████████████████████████████████████████████████████████| 1.80M/1.80M [00:00<00:00, 22.8MB/s]
added_tokens.json: 100%|████████████████████████████████████████████████████████████████| 119/119 [00:00<00:00, 1.52MB/s]
special_tokens_map.json: 100%|██████████████████████████████████████████████████████████| 655/655 [00:00<00:00, 7.99MB/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
LINUX_TRAIN.PY: NOT USING 4-bit quantization
LINUX_TRAIN.PY: LOADING THE BASE MODEL
config.json: 100%|██████████████████████████████████████████████████████████████████████| 644/644 [00:00<00:00, 6.84MB/s]
model.safetensors.index.json: 100%|██████████████████████████████████████████████████| 23.9k/23.9k [00:00<00:00, 161MB/s]
model-00001-of-00003.safetensors: 100%|██████████████████████████████████████████████| 4.94G/4.94G [00:43<00:00, 115MB/s]
model-00002-of-00003.safetensors: 100%|██████████████████████████████████████████████| 5.00G/5.00G [00:43<00:00, 115MB/s]
model-00003-of-00003.safetensors: 100%|██████████████████████████████████████████████| 4.54G/4.54G [00:39<00:00, 115MB/s]
Downloading shards: 100%|██████████████████████████████████████████████████████████████████| 3/3 [02:06<00:00, 42.12s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  6.19it/s]
generation_config.json: 100%|███████████████████████████████████████████████████████████| 136/136 [00:00<00:00, 1.53MB/s]
LINUX_TRAIN.PY: Model device cpu
LINUX_TRAIN.PY: SANITY CHECKING THE BASE MODEL
100%|██████████████████████████████████████████████████████████████████████████████████████| 4/4 [02:40<00:00, 40.04s/it]
LINUX_TRAIN.PY: GETTING THE ATTENTION LAYERS
LINUX_TRAIN.PY: CONFIGURING LoRA
Map: 100%|██████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 1414.65 examples/s]
Map: 100%|████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 1006.37 examples/s]
/home/env/instructlabenv/instructlab_vv/lib/python3.12/site-packages/accelerate/accelerator.py:446: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
LINUX_TRAIN.PY: TRAINING
{'train_runtime': 207.9129, 'train_samples_per_second': 0.053, 'train_steps_per_second': 0.053, 'train_loss': 1.4257791692560369, 'epoch': 1.0}
100%|████████████████████████████████████████████████████████████████████████████████████| 11/11 [03:27<00:00, 18.90s/it]
LINUX_TRAIN.PY: RUNNING INFERENCE ON THE OUTPUT MODEL

===
test 0
===


===
user
===

List a synonym for the word attend.

===
assistant_old
===

Certainly! A synonym for the word "attend" is "participate." Both words have a similar meaning, indicating involvement or engagement in an event or activity. For example, you can "attend" a class or meeting, or you can "participate" in a discussion or workshop.

===
assistant_new
===

Attend: The word attend has several synonyms, including:
    - Be present
    - Show up
    - Be there
    - Participate
    - Be in attendance
    - Be present at
    - Show up for
    - Be a part of
    - Be involved in
    - Join
    - Be there for
    - Be present with
    - Be on hand
    - Be on location
    - Be in the audience
    - Be in the crowd
    - Be in the congregation
    - Be in the gathering
    - Be in the assembly
    - Be in the meeting
    - Be in the session
    - Be in the class
    - Be in the lecture
    - Be in the seminar
    - Be in the workshop
    - Be in the conference
    - Be in the symposium
    - Be in the forum
    - Be in the discussion
    - Be in the debate
    - Be in the interview
    - Be in the talk
    - Be in the speech
    - Be in the presentation
    - Be in the performance
    - Be in the show
    - Be

===
assistant_expected
===

Synonym for Attend is take part in


===
test 1
===


===
user
===

List two synonyms for the word attend and separate with newline.

===
assistant_old
===

attend
    attend
    attend
    attend
    attend
    attend
    attend
    attend
    attend
    attend
    attend
    attend
    attend
    attend
    attend
    attend
    attend
    attend
    attend

===
assistant_new
===

Attend\n
Participate\n

===
assistant_expected
===

Two synonyms for Attend are
take part in
be present at


===
test 2
===


===
user
===

List three synonyms for the word attend and separate with newline.

===
assistant_old
===

Attend, attend to, and attend upon are three synonyms for the word attend.

Attend: To be present, to be in attendance.

Attend to: To give attention to, to take care of, to see to.

Attend upon: To wait upon, to serve, to minister to.

These synonyms can be used interchangeably in various contexts to convey the meaning of being present or giving attention to something or someone. For example:

* I will attend the meeting at 3 PM.
* Please attend to the customer's needs.
* I will attend upon the king during his visit.

These examples illustrate how the synonyms can be used in sentences to convey the meaning of being present or giving attention.

===
assistant_new
===

1. attend
    2. attend
    3. attend

===
assistant_expected
===

Three synonyms for Attend are
take part in
be present at
be there at


===
test 3
===


===
user
===

List four synonyms for the word attend and separate with newline.

===
assistant_old
===

1. attend
2. attend
3. attend
4. attend

I'm sorry for the mistake in my previous comment. I understand that you were asking for synonyms for the word "attend." However, I misunderstood your request. Here are four synonyms for "attend":

1. assist
2. accompany
3. participate
4. observe

I apologize for any confusion and hope this information is helpful. If you have any other questions, please let me know!

===
assistant_new
===

1. attend \n
    2. be present \n
    3. be present at \n
    4. be present in \n

===
assistant_expected
===

Four synonyms for Attend are
take part in
be present at
be there at
make an appearance at
Wrote training_results/final/ggml-model-f16.gguf
```

**Response from the fine-tuned model**

```
(instructlab_vv) [root@dell-r640-041 synonyms]# ilab chat
╭─────────────────────────────────────────────────────── system ────────────────────────────────────────────────────────╮
│ Welcome to InstructLab Chat w/ MODELS/MERLINITE-7B-LAB-Q4_K_M.GGUF (type /h for help)                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── elapsed 5.047 seconds ─╯
>>> List a synonym for the word attend.                                                                      [S][default]
╭───────────────────────────────────────── models/merlinite-7b-lab-Q4_K_M.gguf ─────────────────────────────────────────╮
│ A synonym for the word "attend" is "show up."                                                                         │
│                                                                                                                       │
│ (continued from previous session)                                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────── elapsed 3.311 seconds ─╯
>>> List two synonyms for the word attend                                                                    [S][default]
╭───────────────────────────────────────── models/merlinite-7b-lab-Q4_K_M.gguf ─────────────────────────────────────────╮
│ Two synonyms for the word "attend" are "present yourself" and "make an appearance."                                   │
│                                                                                                                       │
│ (continued from previous session)                                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────── elapsed 4.259 seconds ─╯
>>> List two synonyms for the word beat                                                                      [S][default]
╭───────────────────────────────────────── models/merlinite-7b-lab-Q4_K_M.gguf ─────────────────────────────────────────╮
│ Two synonyms for the word "beat" are "thump" and "drumbeat."                                                          │
│                                                                                                                       │
│ (continued from previous session)                                                                                     │
╰──────────────────────────────────────────────────```

**Contribution checklist**

<!-- Insert an x between the empty brackets: [ ] >> [x] -->

- [ ] The contribution was tested with `ilab generate`
- [ ] No errors or warnings were produced by `ilab generate`
- [ ] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [ ] The `qna.yaml` file contains at least 5 `seed_examples`
- [ ] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [ ] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [ ] Content does not include PII or otherwise sensitive or confidential information
- [ ] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

### CODE REVIEW

**Review by jjasghar — CHANGES_REQUESTED** [review]
Thanks for the submission! It looks interesting. Based on [the current guide](https://github.com/instructlab/taxonomy?tab=readme-ov-file#getting-started-with-skill-contributions), do you mind adding two more examples as the minimum requirement is five examples? 

Thanks for the submission! It looks interesting. Based on [the current guide](https://github.com/instructlab/taxonomy?tab=readme-ov-file#getting-started-with-skill-contributions), do you mind ensure that there are at least five examples with good diversity?

**Comment by yanpliu** [comment]
> Thanks for the submission! It looks interesting. Based on [the current guide](https://github.com/instructlab/taxonomy?tab=readme-ov-file#getting-started-with-skill-contributions), do you mind ensure that there are at least five examples with good diversity?

Thank you very much for your suggestion. Have already rich the examples, and add antonyms for this skill
ilab chat examples:
```
(instructlab_vv) [root@dell-r640-041 taxonomy]# ilab chat
╭──────────────────────────────────────────────────────── system ────────────────────────────────────────────────────────╮
│ Welcome to InstructLab Chat w/ MODELS/MERLINITE-7B-LAB-Q4_K_M.GGUF (type /h for help)                                  │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
>>> list four synonyms for the word attend                                                                    [S][default]
╭───────────────────────────────────────── models/merlinite-7b-lab-Q4_K_M.gguf ──────────────────────────────────────────╮
│ * The word "attend" has several synonyms, including:                                                                   │
│         1. *Participate:* This term is used to describe the act of taking part in an event, activity, or gathering.    │
│ For example, "I participated in a protest last Saturday."                                                              │
│         2. *Show up:* This term is used to describe the act of being physically present at a place or event. For       │
│ example, "I showed up for my friend's birthday party."                                                                 │
│         3. *Be present:* This term is used to describe the act of being in a particular place at a specific time. For  │
│ example, "I was present during our team meeting."                                                                      │
│         4. *Participate in:* This term is used to describe the act of taking part in an event, activity, or gathering. │
│ For example, "I participate in a weekly book club."                                                                    │
│ * These synonyms can be used interchangeably with the word "attend" depending on the context and desired emphasis.*    │
╰─────────────────────────────────────────────────────────────────────────────────────────────── elapsed 34.420 seconds ─╯
>>> list ten synonyms for the word beautiful                                                                  [S][default]
╭───────────────────────────────────────── models/merlinite-7b-lab-Q4_K_M.gguf ──────────────────────────────────────────╮
│ * The word "beautiful" has several synonyms, including:                                                                │
│         1. *Attractive:* This term is used to describe something that is pleasing to look at or that evokes a sense of │
│ appeal. For example, "I find this dress attractive."                                                                   │
│         2. *Handsome:* This term is used to describe something that is pleasing to look at, especially in a masculine  │
│ way. For example, "He has a handsome face."                                                                            │
│         3. *Pleasant:* This term is used to describe something that is enjoyable or agreeable. For example, "I find    │
│ this weather pleasant."                                                                                                │
│         4. *Pretty:* This term is used to describe something that is visually appealing in a small way. For example,   │
│ "This room is pretty with all the flowers."                                                                            │
│         5. *Charming:* This term is used to describe something that is visually appealing and also evokes a sense of   │
│ warmth or friendliness. For example, "His smile is so charming."                                                       │
│         6. *Graceful:* This term is used to describe something that moves with elegance and poise. For example, "She   │
│ dances gracefully."                                                                                                    │
│         7. *Elegant:* This term is used to describe something that has a sense of refined simplicity and               │
│ sophistication. For example, "This dress is so elegant."                                                               │
│         8. *Lovely:* This term is used to describe something that is visually appealing and also evokes a sense of     │
│ warmth or affection. For example, "These flowers are lovely."                                                          │
│         9. *Beautiful:* This term is used to describe something that has a strong sense of visual appeal and also      │
│ evokes a sense of wonder or admiration. For example, "This sunset is so beautiful."                                    │
│         10. *Aesthetically pleasing:* This term is used to describe something that is visually appealing in a way that │
│ goes beyond simple attractiveness. For example, "The architecture of this building is aesthetically pleasing."*        │
│                                                                                                                        │
│ Note: These synonyms can be used interchangeably with the word "beautiful" depending on the context and desired        │
│ emphasis.                                                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────── elapsed 77.877 seconds ─╯
>>> list six antonyms for the word smart                                                                      [S][default]
╭───────────────────────────────────────── models/merlinite-7b-lab-Q4_K_M.gguf ──────────────────────────────────────────╮
│ * The word "smart" has several antonyms, including:                                                                    │
│         1. *Stupid:* This term is used to describe someone or something that lacks intelligence or common sense. For   │
│ example, "He did a stupid thing by not studying for the test."                                                         │
│         2. *Dumb:* This term is used to describe someone or something that lacks intelligence or common sense. For     │
│ example, "That car is so dumb with its engine always breaking down."                                                   │
│         3. *Idiot:* This term is used to describe someone who lacks intelligence or common sense and often behaves in  │
│ an immature or harmful way. For example, "He acts like such an idiot by not listening to anything anyone says."        │
│         4. *Ignorant:* This term is used to describe someone who lacks knowledge or understanding about a particular   │
│ subject. For example, "She's so ignorant about history that she believes in conspiracy theories."                      │
│         5. *Incompetent:* This term is used to describe someone or something that lacks the ability to perform a task  │
│ effectively. For example, "This person is so incompetent that they can't even make a simple sandwich."                 │
│         6. *Foolish:* This term is used to describe someone or something that makes poor decisions or choices based on │
│ a lack of understanding or wisdom. For example, "That plan is so foolish that it will never work."*                    │
│                                                                                                                        │
│ Note: These antonyms can be used interchangeably with the word "smart" depending on the context and desired emphasis.  │
╰─────────────────────────────────────────────────────────────────────────────────────────────── elapsed 55.748 seconds ─╯
```

**Comment by jjasghar** [comment]
Please fix the DCO.

**Comment by yanpliu** [comment]
git commit -s

**Comment by yanpliu** [comment]
> Please fix the DCO.

Have already fixed it.

**Review by jjasghar — APPROVED** [review]

**Comment by jjasghar** [comment]
@instructlab-bot precheck

**Comment by jjasghar** [comment]
Hi! 👋
It’s been a while since you’ve seen any movement on this PR. We haven’t forgotten about you!  We’ve run into some logistical issues, hence this delay. We absolutely want your PR, and being marketed as `e2e-ready` is still the last stop before we get it into the upstream model.

We are thankful for your patience and ask that you please keep this PR open. As soon as we finish all our behind-the-scenes work, we’ll test the full model against your submissions and, ideally, accept your amazing contribution(s)! 

Your Community Maintainer Team.

P.S. if you have any specific questions or thoughts, don’t hesitate to comment on pull request this or email [awesome@instructlab.ai](mailto:awesome@instructlab.ai) and [lhawthor@redhat.com](mailto:lhawthor@redhat.com), and we’ll get back to you as soon as possible.

**Comment by jjasghar** [comment]
This needs to be updated to `version 3`'s requirements.

**Comment by jjasghar** [comment]
Hi! 👋
Thank you for submitting this PR. We are ready to do some validation now, and we have a few candidates to see if they improve the model.
We some resources to run these release candidates, but we need _you_ to help us. Can you reach out to me either on Slack (@awesome) or email me at awesomeATinstructlab.ai so I can get you access via `ilab model chat`?
We can only run these models for a "week" or so, so please reach out as soon as possible and tell me which one is best for you on this PR.

**Pull request merged**
