### PR TITLE
First female minister in Egypt knowledge

### PR DESCRIPTION
**Pull request by ahmed-azraq**
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.


**Describe the contribution to the taxonomy**

Knowledge contribution about the first female cabinet minister in Egypt


**Input given at the prompt**

Who is Hikmat Abu Zayd?


**Response from the original model**


<!-- What you received from the original model in response to your input, 
replace "..." -->

```
│ Hikmat Abu Zayd was an influential Palestinian poet, writer, and intellectual who made significant contributions to Arabic literature and cultural discourse. Born in 1947 in Jerusalem, Abu Zayd was a prominent   │
│ figure in the Palestinian literary scene and is renowned for his poignant verse and thought-provoking essays.                                                                                                       │
│                                                                                                                                                                                                                     │
│ Abu Zayd's poetry often addressed themes of exile, displacement, and resistance, reflecting the experiences of the Palestinian people under occupation. His work was deeply political, yet it also demonstrated a   │
│ profound appreciation for the beauty and complexity of human emotions. Abu Zayd's writing style, characterized by its elegance and intensity, has inspired generations of Arab poets and writers.                   │
│                                                                                                                                                                                                                     │
│ Beyond his literary achievements, Hikmat Abu Zayd played an active role in Palestinian cultural and political life. He was a founding member of the Palestinian Writers Union and a prominent figure in the         │
│ Palestinian liberation movement. His work was a powerful testament to the resilience and determination of the Palestinian people, and it remains an enduring symbol of their struggle for self-determination and    │
│ freedom.                                                                                                                                                                                                            │
│                                                                                                                                                                                                                     │
│ Abu Zayd's literary legacy extends far beyond his native Palestine. His poems have been translated into numerous languages, and he has received numerous awards and accolades in recognition of his contributions   │
│ to Arabic literature. Today, Hikmat Abu Zayd remains a cherished figure in Palestinian culture and a source of inspiration for those who seek justice and freedom.                                                  │
│                                                                                                                                                                                                                     │
│ If you're interested in learning more about Hikmat Abu Zayd or other influential Palestinian writers, I would recommend checking out some of his published works or exploring online resources dedicated to Arabic  │
│ literature and cultural history.                                                                                                                                                                                    │
```


**Response from the fine-tuned model**


The below response is from the trained model. The newly trained model now identified Hekmat Abu Zayd as a female Egyptian minister which is much more accurate than the non-trained model. However, since this low quality maybe because the training is run on a low resource laptop and a quantized version of the model. 

```
│ Hikmat Abu Zayd was a prominent Egyptian politician who served as the Minister of Youth and Sports Affairs in the early 2000s under the presidency of Hosni Mubarak. She was born in 1946 and studied at the        │
│ Faculty of Commerce at Cairo University before becoming involved in politics in the 1970s.                                                                                                                          │
│                                                                                                                                                                                                                     │
│ Abu Zayd held various ministerial positions, including Minister of Social Affairs, Minister of Family and Population Affairs, and finally Minister of Youth and Sports Affairs. During her tenure as Minister of    │
│ Youth and Sports Affairs, she played a significant role in promoting sports and physical activity among Egyptian youth, as well as implementing social programs aimed at improving the lives of marginalized        │
│ groups.                                                                                                                                                                                                             │
│                                                                                                                                                                                                                     │
│ Hikmat Abu Zayd was known for her strong leadership skills and her commitment to serving her community. She passed away in 2017, leaving behind a legacy of dedication and hard work in the field of politics and   │
│ social welfare.          
```

**Contribution checklist**

<!-- Insert an x between the empty brackets: [ ] >> [x] -->

- [x] The contribution was tested with `ilab generate`
- [x] No errors or warnings were produced by `ilab generate`
- [x] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x] The `qna.yaml` file contains at least 5 `seed_examples`
- [x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [x] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [x] Content does not include PII or otherwise sensitive or confidential information
- [x] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

### CODE REVIEW

**Comment by mcorbin-ibm** [comment]
@jjasghar I have reviewed this submission from a taxonomic perspective, and I think this entry is categorized appropriately!  No changes to where the qna/attribution file lives.

**Comment by jjasghar** [comment]
@instructlab-bot precheck

**Comment by jjasghar** [comment]
Hi! Until we have our community model builds back up and running, many PRs will be held off. We are hoping to have them running again soon, and if you have any specific questions don't hesitate to comment here or reach out to #triage in slack.

**Comment by mcorbin-ibm** [comment]
@jjasghar This PR was likely created in the authoring/building of @ahmed-azraq 's tutorial on using InstructLab to contribute knowledge: https://developer.ibm.com/tutorials/awb-contributing-knowledge-instructlab-granite/. In fact, he links to this PR in the final step.

**Comment by ahmed-azraq** [comment]
Hi @mcorbin-ibm - Yep, it is. It would be great to see the end-to-end result for it, since the community builds are back.

**Comment by jjasghar** [comment]
```
Training finished! Best final checkpoint: samples_82822 with score: 6.810897435897436
```

**Comment by jjasghar** [comment]
```
╭───────────────────────────────────────────────────────────────────────────────────────────────────── system ──────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Welcome to InstructLab Chat w/ SAMPLES_82822 (type /h for help)                                                                                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
>>> How many years Abu Zayd spent in Libya?                                                                                                                                                              [S][default]
╭────────────────────────────────────────────────────────────────────────────────────────────────── samples_82822 ──────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Abu Zayd appears to have spent more than 40 years in Libya, as he mentions that he has been living and working there for "over 40 years" in 1975.                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── elapsed 0.327 seconds ─╯
>>> What award did Abu Zayd receive?                                                                                                                                                                     [S][default]
╭────────────────────────────────────────────────────────────────────────────────────────────────── samples_82822 ──────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Abu Zayd received the Lenin Peace Prize in 1975 for his work in promoting peace in the Middle East and North Africa.                                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── elapsed 0.264 seconds ─╯
>>> When was the Egyptian National Front set?                                                                                                                                                            [S][default]
╭────────────────────────────────────────────────────────────────────────────────────────────────── samples_82822 ──────────────────────────────────────────────────────────────────────────────────────────────────╮
│ The Egyptian National Front was established in 1976.                                                                                                                                                              │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── elapsed 0.116 seconds ─╯
>>> How Abu Zayd supported the NGOs?                                                                                                                                                                     [S][default]
╭────────────────────────────────────────────────────────────────────────────────────────────────── samples_82822 ──────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 1. Abu Zayd's support for NGOs was primarily through his role as a government official.                                                                                                                           │
│ 2. As the Minister of Information in the early 1990s, he made efforts to create a favorable environment for NGOs.                                                                                                 │
│ 3. This included implementing policies that reduced bureaucratic red tape and promoted greater transparency and accountability.                                                                                   │
│ 4. Abu Zayd also worked to increase funding for NGOs, recognizing their important role in providing social and economic services to the community.                                                                │
│ 5. Overall, his support for NGOs was aimed at strengthening civil society and promoting democratic values in Egypt.                                                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── elapsed 1.022 seconds ─╯
>>> When has Hikmat Abu Zayd receive doctorate degree?                                                                                                                                                   [S][default]
╭────────────────────────────────────────────────────────────────────────────────────────────────── samples_82822 ──────────────────────────────────────────────────────────────────────────────────────────────────╮
│ The exact date of when Hikmat Abu Zayd received her doctorate degree is not provided in the context. However, it is mentioned that she has completed her doctorate degree in economics from the University of     │
│ Paris.                                                                                                                                                                                                            │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── elapsed 0.343 seconds ─╯
```

Per these questions, it looks like the training did not work. I'm sorry but I am rejecting this PR.

**Comment by jjasghar** [comment]
That is a great question, and I believe we need the SDG team and Red Hat Engineering team to chime in here.

I tested against your seed questions to see if they came back with the answers you gave, and as you can see a sampling of them are majority wrong. That could be a sign of a bunch of things, and we need engineering to come in about this.

/cc @cdoern @RobotSail

**Pull request closed without merging**
