### PR TITLE
Skill for rearranging meaningful words

### PR DESCRIPTION
**Pull request by amtdas**
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

- This PR consist of skills for rearranging alphabets into meaningful words.
- The new words should be dictionary words and not any random anagrams.
- Its similar to unscrambling the word and reforming into new meaningful words.
- Following commands successfully executed.
 
instructlab % ilab serve --max-ctx-size 7000
instructlab % ilab generate

**Input given at the prompt**

```
>>> Arrange letters in SILENT and give another 6 letters meaningful words.
```

**Response from the original model**

```
...
```

**Response from the fine-tuned model**

```
 >>> Arrange letters in NIGHT and give another 5 letters meaningful words.                                                                       [S][default]

INFO 2024-04-21 19:56:56,415 _client.py:1026 HTTP Request: POST http://127.0.0.1:8000/v1/chat/completions "HTTP/1.1 200 OK"
╭──────────────────────────────────────────────────────────────── merlinite-7b-lab-Q4_K_M ─────────────────────────────────────────────────────────────────╮
│ The letters in "NIGHT" can be rearranged to form the word "THING." Here are five more five-letter words that can be formed from the same set of letters: │
│                                                                                                                                                          │
│ 1. THING                                                                                                                                                 │
│ 2. THING                                                                                                                                                 │
│ 3. THING                                                                                                                                                 │
│ 4. THING                                                                                                                                                 │
│ 5. THING                                                                                                                                                 │
│                                                                                                                                                          │
│ These words have different meanings, ranging from "thing" (a general term for any object or concept) to "thing" (a recurring noun phrase). The           │
│ duplicates of "THING" highlight the versatility of the letters, as they can form the word "THING" multiple times with different arrangements of the same │
│ letters.                                                                                                                                                 │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── elapsed 4.541 seconds ─╯
```

**Contribution checklist**

- [x] The contribution was tested with `ilab generate`
- [x] No errors or warnings were produced by `ilab generate`
- [x] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x] The `qna.yaml` file contains at least 5 `seed_examples`
- [x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [x] An `attribution.txt` file in the same folder as the `qna.yaml` file.

### CODE REVIEW

**Comment by amtdas** [comment]
This PR is similar to the closed private taxonomy [PR-553](https://github.com/instructlab/taxonomy/pull/553) .

**Comment by jjasghar** [comment]
@instructlab-bot precheck

**Review by mingxzhao — COMMENTED** [review]
Due to the nature of the way LLMs process language, this type of skill is very difficult to teach and process. LLMs read inputs through a process called tokenization, which means that strings of characters are broken up into groups that are commonly seen together, which many times ends up being full words or part words. As such it has difficulty recognizing individual letters without specialized knowledge, so this would be very difficult to even generate synthetic data for, as we can see in the synthetic data generated by the teacher model. I will close this PR due to the poor synthetic data, but thank you very much for your contribution!

**Comment by amtdas** [comment]
@mingxzhao - Thanks for reviewing this and adding comments. Since you said "poor synthetic data" ,  is there any workaround to improve this. Do you think if we add more samples(maybe another 10) will help teaching model better? Kindly let me know and I can work on it further.

**Comment by mingxzhao** [comment]
The issue is that skills that require letters to be rearranged are impossible to teach at the time. Due to the way the model breaks down words, also known as the tokenization process, the model does not actually associate any meaning with individual letters, thus it cannot learn to rearrange letters or generate data on wether a word has the same letters as another word. Does this help explain?

**Comment by amtdas** [comment]
Yes! it helps. Thanks for response. Looking for new idea henceforth.

**Pull request closed without merging**
