### PR TITLE
Adding nba finals 2024 knowledge

### PR DESCRIPTION
**Pull request by lgdeloss**
If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

- adding detials about celtics winning
- adding the rosters of both teams
- adding coaches for both teams

**Input given at the prompt**

```
 Who won the nba finals in 2024?
```

**Response from the original model**

```
The 2021-2022 NBA Championship was recently held, and the winner was the Golden State Warriors. They
defeated the Boston Celtics in a thrilling six-game series. The Warriors, led by superstar players
Stephen Curry, Klay Thompson, and Draymond Green, secured their fourth NBA title in eight years. This
victory marks an impressive comeback for the Warriors, who faced several injuries and challenges during
their journey to the championship. The NBA Finals was filled with exciting moments, including Curry's
historic performance in Game 6, where he scored 43 points, including 10 three-pointers, setting a new NBA
Finals record. The Warriors' victory was a testament to their resilience, teamwork, and determination,
making this season one to remember in NBA history. 
```

**Response from the fine-tuned model**

```
 Boston Celtics
```

**Contribution checklist**

- [ ] The contribution was tested with `ilab generate`
- [ ] No errors or warnings were produced by `ilab generate`
- [ ] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [ ] The `qna.yaml` file contains at least 5 `seed_examples`
- [ ] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [ ] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [ ] Content does not include PII or otherwise sensitive or confidential information
- [ ] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

### CODE REVIEW

**Comment by jjasghar** [comment]
Hello! Thank you for this submission. Unfortunately, we need you to fill out the [knowledge submission form](https://docs.google.com/forms/d/1VWJ_XPwH3gBTIXCabpWc0I5pjWIlXETMSFKXc8fpgkA/viewform?edit_requested=true) before we can accept any submission from you. Please take a moment to fill it out so we can get this through the proper channels.

I will close this for now, but if/when you get the submission approval, you can reopen the PR, and we can look at adding it to the knowledge submission process.

**Comment by lgdeloss** [comment]
@jjasghar Great! I've filled out the form and will re-open.

**Comment by lgdeloss** [comment]
@jjasghar Actually, not seeing re-open option from my side.

**Comment by jjasghar** [comment]
I think you need to be approved by the legal team and/or @juliadenham before we can reopen it.

**Pull request closed without merging**
